# This script was automatically generated by the shinymgr R package's App Builder on 2023-03-27 10:04:56.
# For more information, visit: https://code.usgs.gov/vtcfwru/shinymgr
jscode <- "
shinyjs.disableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.bind('click.tab', function(e) {
e.preventDefault();
return false;
});
tab.addClass('disabled');
}

shinyjs.enableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.unbind('click.tab');
tab.removeClass('disabled');
}
"

css <- "
.nav li a.disabled {
background-color: #bbb !important;
border-color: #ccc !important;
cursor: not-allowed !important;
}"


addTaxon_ui <- function(id) {
  ns <- NS(id)
  tagList(
    fluidPage(
      useShinyjs(),
      extendShinyjs(text = jscode, functions = c('disableTab','enableTab')),
      inlineCSS(css),
      actionButton(
        ns("start"),
        "Start New Analysis",
        onclick = "var $btn=$(this); setTimeout(function(){$btn.remove();},0);"
      ),
      uiOutput(ns('test'))
    )
  )
}
addTaxon_server <- function(id, userID, shinyMgrPath) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns
    observeEvent(input$start, {

      disable('start')

      output$test <- renderUI({
        tagList(
          tabsetPanel(
            id = ns("mainTabSet"),
            tabPanel(
              "Search for Taxa", 
              value = "tab1",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                "All taxa in AMMonitor are linked to the Integrated Taxonomic Information System (ITIS). To add a new taxon to your database, you can (1) use the search tool below to look up a taxon. Click on a row from the search results to auto-populate the taxonomic serial number (TSN) for that taxon, or (2) enter the TSN directly. After a TSN as been selected, click “next”."
              ),
              taxon_itis_lookup_ui(ns("mod1")),
              fluidRow(
                actionButton(ns('next_tab_1'), label = "Next")
              )
            ),
            tabPanel(
              "Add Taxon to Database", 
              value = "tab2",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                "Review taxon information and add it to your AMMonitor database."
              ),
              taxon_add_new_ui(ns("mod2")),
              fluidRow(
                actionButton(ns('previous_tab_2'), label = "Previous"),
                actionButton(ns('next_tab_2'), label = "Next")
              )
            ),
            tabPanel(
              "Save",
              value = "tab3",
              save_analysis_ui(ns("mod3")),
              tags$br(),
              tags$br(),
              fluidRow(
                actionButton(ns("previous_tab_3"), label = "Previous")
              )
            )
          )
        )
      })
      delay(50, {
        js$disableTab("tab2")
        js$disableTab("tab3")
      })
    })

    data1 <- taxon_itis_lookup_server("mod1")
    data2 <- taxon_add_new_server("mod2", tsn = data1$tsn)
    save_analysis_server("mod3",
      appName = "addTaxon",
      moduleInput = input,
      returns = list(
        data1 = list(
          tsn = data1$tsn()
        ),
        data2 = list(
          taxonAddResults = data2$taxonAddResults()
        )
      ),
      metadata = list(
        appDescription = "",
        mod1 = list(
          dataset = "data1",
          modName = "taxon_itis_lookup",
          modDisplayName = "Taxon Look-up",
          modDescription = "Look-up a taxon from itis to add to the database.",
          modArguments = "This module has no additional arguments",
          modReturns = data.frame(
            name = c("tsn"),
            class = c("character"),
            description = c("Taxonomic Serial Number of selected taxon")
          ),
          modPackages = data.frame(
            name = c("ritis","taxize"),
            version = c("1.0.0","0.9.100")
          )
        ),
        mod2 = list(
          dataset = "data2",
          modName = "taxon_add_new",
          modDisplayName = "Add Taxon",
          modDescription = "Add a new taxon (from ITIS) to the database.",
          modArguments = data.frame(
            name = c("tsn"),
            class = c("character"),
            description = c("taxonomic serial number (TSN) from ITIS")
          ),
          modReturns = data.frame(
            name = c("taxonAddResults"),
            class = c("data.frame"),
            description = c("Results of attempted taxon additions")
          ),
          modPackages = data.frame(
            name = c("ritis","taxize"),
            version = c("1.0.0","0.9.100")
          )
        )
      )
    )
    observeEvent(input$next_tab_1, {
      js$enableTab('tab2')
      js$disableTab('tab1')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab2'
      )
    })
    observeEvent(input$next_tab_2, {
      js$enableTab('tab3')
      js$disableTab('tab2')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab3'
      )
    })
    observeEvent(input$previous_tab_2, {
      delay(50, {
        js$enableTab('tab1')
        js$disableTab('tab2')
      })
      removeTab('mainTabSet','tab2',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Add Taxon to Database",
          value = "tab2",
          taxon_add_new_ui(ns("mod2")),
          fluidRow(
            actionButton(ns('previous_tab_2'), label = "Previous"),
            actionButton(ns('next_tab_2'), label = "Next")
          )
        ),
        target = 'tab1',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab1'
      )
    })
    observeEvent(input$previous_tab_3, {
      delay(50, {
        js$enableTab('tab2')
        js$disableTab('tab3')
      })
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab2'
      )
    })
  })
}
