# This script was automatically generated by the shinymgr (vers. 1.0.0) R package's App Builder on 2023-12-05 14:50:37.100221.
# For more information, visit: https://code.usgs.gov/vtcfwru/shinymgr

library(DBI)

jscode <- "
shinyjs.disableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.bind('click.tab', function(e) {
e.preventDefault();
return false;
});
tab.addClass('disabled');
}

shinyjs.enableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.unbind('click.tab');
tab.removeClass('disabled');
}
"

css <- "
.nav li a.disabled {
background-color: #bbb !important;
border-color: #ccc !important;
cursor: not-allowed !important;
}"


compareSurveyVisits_ui <- function(id) {
  ns <- NS(id)
  tagList(
    fluidPage(
      useShinyjs(),
      extendShinyjs(text = jscode, functions = c('disableTab','enableTab')),
      inlineCSS(css),
      actionButton(
        ns("start"),
        "Start New Analysis",
        onclick = "var $btn=$(this); setTimeout(function(){$btn.remove();},0);"
      ),
      uiOutput(ns('appUI'))
    )
  )
}
compareSurveyVisits_server <- function(id, userID, shinyMgrPath) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns
    observeEvent(input$start, {

      disable('start')

      output$appUI <- renderUI({
        tagList(
          tabsetPanel(
            id = ns("mainTabSet"),
            tabPanel(
              "Upload Survey123 Form", 
              value = "tab1",
              survey_upload_ui(ns("mod1")),
              fluidRow(
                actionButton(ns('next_tab_1'), label = "Next")
              )
            ),
            tabPanel(
              "Compare Form to Visits", 
              value = "tab2",
              survey_compareVisits_ui(ns("mod2")),
              fluidRow(
                actionButton(ns('previous_tab_2'), label = "Previous"),
                actionButton(ns('next_tab_2'), label = "Next")
              )
            ),
            tabPanel(
              "Compare Choices to Lists", 
              value = "tab3",
              survey_compareLists_ui(ns("mod3")),
              fluidRow(
                actionButton(ns('previous_tab_3'), label = "Previous")
              )
            )
          ),
          tags$p(tags$i("App created with shinymgr"), style = "text-align:right")
        )
      })
      delay(50, {
        js$disableTab("tab2")
        js$disableTab("tab3")
        js$disableTab("tab4")
      })
    })

    data1 <- survey_upload_server("mod1")
    data2 <- survey_compareVisits_server("mod2", survey_qs = data1$survey_qs)
    survey_compareLists_server("mod3", survey_qs = data1$survey_qs, survey_choices = data1$survey_choices)
    
    observeEvent(input$next_tab_1, {
      js$enableTab('tab2')
      js$disableTab('tab1')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab2'
      )
    })
    observeEvent(input$next_tab_2, {
      js$enableTab('tab3')
      js$disableTab('tab2')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab3'
      )
    })
    observeEvent(input$previous_tab_2, {
      delay(50, {
        js$enableTab('tab1')
        js$disableTab('tab2')
      })
      removeTab('mainTabSet','tab2',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Compare Form to Visits",
          value = "tab2",
          survey_compareVisits_ui(ns("mod2")),
          fluidRow(
            actionButton(ns('previous_tab_2'), label = "Previous"),
            actionButton(ns('next_tab_2'), label = "Next")
          )
        ),
        target = 'tab1',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab1'
      )
    })
    observeEvent(input$previous_tab_3, {
      delay(50, {
        js$enableTab('tab2')
        js$disableTab('tab3')
      })
      removeTab('mainTabSet','tab3',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Compare Choices to Lists",
          value = "tab3",
          survey_compareLists_ui(ns("mod3")),
          fluidRow(
            actionButton(ns('previous_tab_3'), label = "Previous")
          )
        ),
        target = 'tab2',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab2'
      )
    })
    observeEvent(input$previous_tab_4, {
      delay(50, {
        js$enableTab('tab3')
        js$disableTab('tab4')
      })
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab3'
      )
    })
  })
}
