# This script was automatically generated by the shinymgr (vers. 1.0.0) R package's App Builder on 2023-10-06 14:22:44.
# For more information, visit: https://code.usgs.gov/vtcfwru/shinymgr

library(AMModels)
library(monitoR)
library(reshape2)
library(seewave)
library(shinydashboard)
library(shinyjs)
library(tools)
library(tuneR)
library(howler)

jscode <- "
shinyjs.disableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.bind('click.tab', function(e) {
e.preventDefault();
return false;
});
tab.addClass('disabled');
}

shinyjs.enableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.unbind('click.tab');
tab.removeClass('disabled');
}
"

css <- "
.nav li a.disabled {
background-color: #bbb !important;
border-color: #ccc !important;
cursor: not-allowed !important;
}"


create_templates_ui <- function(id) {
  ns <- NS(id)
  tagList(
    fluidPage(
      useShinyjs(),
      extendShinyjs(text = jscode, functions = c('disableTab','enableTab')),
      inlineCSS(css),
      actionButton(
        ns("start"),
        "Start New Analysis",
        onclick = "var $btn=$(this); setTimeout(function(){$btn.remove();},0);"
      ),
      uiOutput(ns('appUI'))
    )
  )
}
create_templates_server <- function(id, userID, shinyMgrPath) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns
    observeEvent(input$start, {
      
      disable('start')
      
      output$appUI <- renderUI({
        tagList(
          tabsetPanel(
            id = ns("mainTabSet"),
            tabPanel(
              "Select Annotations", 
              value = "tab1",
              template_candidates_ui(ns("mod1")),
              fluidRow(
                actionButton(ns('next_tab_1'), label = "Next")
              )
            ),
            tabPanel(
              "Create Templates", 
              value = "tab2",
              simple_audio_player_ui(ns("mod2")),
              template_create_ui(ns("mod3")),
              fluidRow(
                actionButton(ns('previous_tab_2'), label = "Previous"),
                actionButton(ns('next_tab_2'), label = "Next")
              )
            ),
            tabPanel(
              "Score Templates", 
              value = "tab3",
              template_score_ui(ns("mod4")),
              fluidRow(
                actionButton(ns('previous_tab_3'), label = "Previous"),
                actionButton(ns('next_tab_3'), label = "Next")
              )
            ),
            tabPanel(
              "Save Templates", 
              value = "tab4",
              template_save_ui(ns("mod5")),
              fluidRow(
                actionButton(ns('previous_tab_4'), label = "Previous")
              )
            )
          ),
          tags$p(tags$i("App created with shinymgr"), style = "text-align:right")
        )
      })
      delay(50, {
        js$disableTab("tab2")
        js$disableTab("tab3")
        js$disableTab("tab4")
      })
    })
    
    data1 <- template_candidates_server("mod1")
    data2 <- simple_audio_player_server("mod2", recordingID = data3$curRecording, selectedRow = data3$curAnno, showOnlySelected = reactive(TRUE))
    data3 <- template_create_server("mod3", annotations = data1$selectedAnnos, audioPath = data2$audioURL, spec_wl = data2$spec_wl, spec_wn = data2$spec_wn, spec_ovlp = data2$spec_ovlp, amp_filter = data2$amp_filter)
    data4 <- template_score_server("mod4", taxon = data1$selectedTaxon, binTemplates = data3$binTemplates, corTemplates = data3$corTemplates)
    data5 <- template_save_server("mod5", taxon = data1$selectedTaxon, binTemps = data4$finalBinTemplates, corTemps = data4$finalCorTemplates, metadata = data3$metadata)
    observeEvent(input$next_tab_1, {
      js$enableTab('tab2')
      js$disableTab('tab1')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab2'
      )
    })
    observeEvent(input$next_tab_2, {
      js$enableTab('tab3')
      js$disableTab('tab2')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab3'
      )
    })
    observeEvent(input$previous_tab_2, {
      delay(50, {
        js$enableTab('tab1')
        js$disableTab('tab2')
      })
      removeTab('mainTabSet','tab2',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Create Templates",
          value = "tab2",
          simple_audio_player_ui(ns("mod2")),
          template_create_ui(ns("mod3")),
          fluidRow(
            actionButton(ns('previous_tab_2'), label = "Previous"),
            actionButton(ns('next_tab_2'), label = "Next")
          )
        ),
        target = 'tab1',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab1'
      )
    })
    observeEvent(input$next_tab_3, {
      js$enableTab('tab4')
      js$disableTab('tab3')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab4'
      )
    })
    observeEvent(input$previous_tab_3, {
      delay(50, {
        js$enableTab('tab2')
        js$disableTab('tab3')
      })
      removeTab('mainTabSet','tab3',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Score Templates",
          value = "tab3",
          template_score_ui(ns("mod4")),
          fluidRow(
            actionButton(ns('previous_tab_3'), label = "Previous"),
            actionButton(ns('next_tab_3'), label = "Next")
          )
        ),
        target = 'tab2',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab2'
      )
    })
    observeEvent(input$previous_tab_4, {
      delay(50, {
        js$enableTab('tab3')
        js$disableTab('tab4')
      })
      removeTab('mainTabSet','tab4',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Save Templates",
          value = "tab4",
          template_save_ui(ns("mod5")),
          fluidRow(
            actionButton(ns('previous_tab_4'), label = "Previous")
          )
        ),
        target = 'tab3',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab3'
      )
    })
  })
}
