# This script was automatically generated by the shinymgr (vers. 1.0.0) R package's App Builder on 2023-12-19 14:45:15.266465.
# For more information, visit: https://code.usgs.gov/vtcfwru/shinymgr

library(AMModels)
library(DBI)
library(caret)
library(data.table)
library(seewave)
library(shiny)
library(tools)
library(tuneR)

jscode <- "
shinyjs.disableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.bind('click.tab', function(e) {
e.preventDefault();
return false;
});
tab.addClass('disabled');
}

shinyjs.enableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.unbind('click.tab');
tab.removeClass('disabled');
}
"

css <- "
.nav li a.disabled {
background-color: #bbb !important;
border-color: #ccc !important;
cursor: not-allowed !important;
}"


create_classifiers_ui <- function(id) {
  ns <- NS(id)
  tagList(
    fluidPage(
      useShinyjs(),
      extendShinyjs(text = jscode, functions = c('disableTab','enableTab')),
      inlineCSS(css),
      actionButton(
        ns("start"),
        "Start New Analysis",
        onclick = "var $btn=$(this); setTimeout(function(){$btn.remove();},0);"
      ),
      uiOutput(ns('appUI'))
    )
  )
}
create_classifiers_server <- function(id, userID, shinyMgrPath) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns
    observeEvent(input$start, {

      disable('start')

      output$appUI <- renderUI({
        tagList(
          tabsetPanel(
            id = ns("mainTabSet"),
            tabPanel(
              "Select Parent Model", 
              value = "tab1",
              classifier_selectTaxon_ui(ns("mod1")),
              fluidRow(
                actionButton(ns('next_tab_1'), label = "Next")
              )
            ),
            tabPanel(
              "Select Classifier Models", 
              value = "tab2",
              classifier_selectModels_ui(ns("mod2")),
              fluidRow(
                actionButton(ns('previous_tab_2'), label = "Previous"),
                actionButton(ns('next_tab_2'), label = "Next")
              )
            ),
            tabPanel(
              "Split Data", 
              value = "tab3",
              classifier_splitData_ui(ns("mod3")),
              fluidRow(
                actionButton(ns('previous_tab_3'), label = "Previous"),
                actionButton(ns('next_tab_3'), label = "Next")
              )
            ),
            tabPanel(
              "Train Classifiers", 
              value = "tab4",
              classifier_trainModels_ui(ns("mod4")),
              fluidRow(
                actionButton(ns('previous_tab_4'), label = "Previous"),
                actionButton(ns('next_tab_4'), label = "Next")
              )
            ),
            tabPanel(
              "Test Classifiers", 
              value = "tab5",
              classifier_testModels_ui(ns("mod5")),
              fluidRow(
                actionButton(ns('previous_tab_5'), label = "Previous"),
                actionButton(ns('next_tab_5'), label = "Next")
              )
            ),
            tabPanel(
              "Save Models", 
              value = "tab6",
              classifier_saveModels_ui(ns("mod6")),
              fluidRow(
                actionButton(ns('previous_tab_6'), label = "Previous")
              )
            )
          ),
          tags$p(tags$i("App created with shinymgr"), style = "text-align:right")
        )
      })
      delay(50, {
        js$disableTab("tab2")
        js$disableTab("tab3")
        js$disableTab("tab4")
        js$disableTab("tab5")
        js$disableTab("tab6")
      })
    })

    data1 <- classifier_selectTaxon_server("mod1")
    data2 <- classifier_selectModels_server("mod2")
    data3 <- classifier_splitData_server("mod3", verifications = data1$verifications, verification_bboxes = data1$verification_bboxes)
    data4 <- classifier_trainModels_server("mod4", model_id = data1$model_id, selectedModels = data2$selectedModels, train_valid = data3$train_valid, train_bboxes = data3$train_bbox)
    data5 <- classifier_testModels_server("mod5", trained_models = data4$trained_models, test_valid = data3$test_valid, test_bboxes = data3$test_bbox)
    data6 <- classifier_saveModels_server("mod6", final_models = data5$final_models, model_id = data1$model_id)

    observeEvent(input$next_tab_1, {
      js$enableTab('tab2')
      js$disableTab('tab1')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab2'
      )
    })
    observeEvent(input$next_tab_2, {
      js$enableTab('tab3')
      js$disableTab('tab2')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab3'
      )
    })
    observeEvent(input$previous_tab_2, {
      delay(50, {
        js$enableTab('tab1')
        js$disableTab('tab2')
      })
      removeTab('mainTabSet','tab2',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Select Classifier Models",
          value = "tab2",
          classifier_selectModels_ui(ns("mod2")),
          fluidRow(
            actionButton(ns('previous_tab_2'), label = "Previous"),
            actionButton(ns('next_tab_2'), label = "Next")
          )
        ),
        target = 'tab1',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab1'
      )
    })
    observeEvent(input$next_tab_3, {
      js$enableTab('tab4')
      js$disableTab('tab3')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab4'
      )
    })
    observeEvent(input$previous_tab_3, {
      delay(50, {
        js$enableTab('tab2')
        js$disableTab('tab3')
      })
      removeTab('mainTabSet','tab3',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Split Data",
          value = "tab3",
          classifier_splitData_ui(ns("mod3")),
          fluidRow(
            actionButton(ns('previous_tab_3'), label = "Previous"),
            actionButton(ns('next_tab_3'), label = "Next")
          )
        ),
        target = 'tab2',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab2'
      )
    })
    observeEvent(input$next_tab_4, {
      js$enableTab('tab5')
      js$disableTab('tab4')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab5'
      )
    })
    observeEvent(input$previous_tab_4, {
      delay(50, {
        js$enableTab('tab3')
        js$disableTab('tab4')
      })
      removeTab('mainTabSet','tab4',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Train Classifiers",
          value = "tab4",
          classifier_trainModels_ui(ns("mod4")),
          fluidRow(
            actionButton(ns('previous_tab_4'), label = "Previous"),
            actionButton(ns('next_tab_4'), label = "Next")
          )
        ),
        target = 'tab3',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab3'
      )
    })
    observeEvent(input$next_tab_5, {
      js$enableTab('tab6')
      js$disableTab('tab5')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab6'
      )
    })
    observeEvent(input$previous_tab_5, {
      delay(50, {
        js$enableTab('tab4')
        js$disableTab('tab5')
      })
      removeTab('mainTabSet','tab5',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Test Classifiers",
          value = "tab5",
          classifier_testModels_ui(ns("mod5")),
          fluidRow(
            actionButton(ns('previous_tab_5'), label = "Previous"),
            actionButton(ns('next_tab_5'), label = "Next")
          )
        ),
        target = 'tab4',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab4'
      )
    })
    observeEvent(input$previous_tab_6, {
      delay(50, {
        js$enableTab('tab5')
        js$disableTab('tab6')
      })
      removeTab('mainTabSet','tab6',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Save Models",
          value = "tab6",
          classifier_saveModels_ui(ns("mod6")),
          fluidRow(
            actionButton(ns('previous_tab_6'), label = "Previous"),
            actionButton(ns('next_tab_6'), label = "Next")
          )
        ),
        target = 'tab5',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab5'
      )
    })
  })
}
