# This script was automatically generated by the shinymgr (vers. 1.1.0) R package's App Builder on 2024-11-15 11:42:59.651189.
# For more information, visit: https://code.usgs.gov/vtcfwru/shinymgr

library(DBI)
library(reactable)
library(shinyjs)
library(tools)

jscode <- "
shinyjs.disableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.bind('click.tab', function(e) {
e.preventDefault();
return false;
});
tab.addClass('disabled');
}

shinyjs.enableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.unbind('click.tab');
tab.removeClass('disabled');
}
"

css <- "
.nav li a.disabled {
background-color: #bbb !important;
border-color: #ccc !important;
cursor: not-allowed !important;
}"


csv_2_db_ui <- function(id) {
  ns <- NS(id)
  tagList(
    fluidPage(
      shinyjs::useShinyjs(),
      shinyjs::extendShinyjs(text = jscode, functions = c('disableTab','enableTab')),
      shinyjs::inlineCSS(css),
      actionButton(
        ns("start"),
        "Start New Analysis",
        onclick = "var $btn=$(this); setTimeout(function(){$btn.remove();},0);"
      ),
      uiOutput(ns('appUI'))
    )
  )
}
csv_2_db_server <- function(id, userID, shinyMgrPath) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns
    observeEvent(input$start, {

      shinyjs::disable('start')

      output$appUI <- renderUI({
        tagList(
          tabsetPanel(
            id = ns("mainTabSet"),
            tabPanel(
              "Upload CSV", 
              value = "tab1",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                "To add new records to the database from a CSV file, (1) select the table you would like add to, then (2) select the CSV file containing the new records. The contents of the csv file, along with any warnings, will be displayed below. Finally, (3) click the “Append to Table” button. The status of the database update (successful or not) will be displayed."
              ),
              csv_2_db_upload_ui(ns("mod1")),
              fluidRow(
                # actionButton(ns('next_tab_1'), label = "Next")
              )
            ),
            # tabPanel(
            #   "Save",
            #   value = "tab2",
            #   save_analysis_ui(ns("mod2")),
            #   tags$br(),
            #   tags$br(),
            #   fluidRow(
            #     actionButton(ns("previous_tab_2"), label = "Previous")
            #   )
            # )
          ),
          tags$p(tags$i("App created with shinymgr"), style = "text-align:right")
        )
      })
      shinyjs::delay(50, {
        shinyjs::js$disableTab("tab2")
      })
    })

    csv_2_db_upload_server("mod1")
    save_analysis_server("mod2",
      appName = "csv_2_db",
      moduleInput = input,
      returns = list(
      ),
      metadata = list(
        appDescription = "Add records from a csv file to a database table.",
        mod1 = list(
          dataset = "no returns",
          modName = "csv_2_db_upload",
          modDisplayName = "csv_2_db.",
          modDescription = "Import a CSV to a database table.",
          modArguments = "This module has no additional arguments",
          modReturns = "This module has no returns",
          modPackages = data.frame(
            name = c("DBI","reactable","shinyjs","tools"),
            version = c("1.2.2","0.4.4","2.1.0","4.4.0")
          )
        ),
        lockfile = list(R = list(Version = "4.4.0", Repositories = list(CRAN = "https://cran.rstudio.com/")), Packages = list(shinydashboard = list(Package = "shinydashboard", Version = "0.7.2", Source = "Repository", Repository = "CRAN", Requirements = c("R", "htmltools", "promises", "shiny", "utils"), Hash = "e418b532e9bb4eb22a714b9a9f1acee7"), bit = list(Package = "bit", Version = "4.0.5", Source = "Repository", Repository = "CRAN", Requirements = "R", Hash = "d242abec29412ce988848d0294b208fd"), cpp11 = list(Package = "cpp11", Version = "0.4.7", Source = "Repository", Repository = "CRAN", Requirements = "R", Hash = "5a295d7d963cc5035284dcdbaf334f4e"), 
    jsonlite = list(Package = "jsonlite", Version = "1.8.8", Source = "Repository", Repository = "CRAN", Requirements = "methods", Hash = "e1b9c55281c5adc4dd113652d9e26768"), renv = list(Package = "renv", Version = "1.0.7", Source = "Repository", Repository = "CRAN", Requirements = "utils", Hash = "397b7b2a265bc5a7a06852524dabae20"), highr = list(Package = "highr", Version = "0.10", Source = "Repository", Repository = "CRAN", Requirements = c("R", "xfun"), Hash = "06230136b2d2b9ba5805e1963fa6e890"), 
    crayon = list(Package = "crayon", Version = "1.5.2", Source = "Repository", Repository = "CRAN", Requirements = c("grDevices", "methods", "utils"), Hash = "e8a1e41acf02548751f45c718d55aa6a"), promises = list(Package = "promises", Version = "1.3.0", Source = "Repository", Repository = "CRAN", Requirements = c("R6", "Rcpp", "fastmap", "later", "magrittr", "rlang", "stats"), Hash = "434cd5388a3979e74be5c219bcd6e77d"), Rcpp = list(Package = "Rcpp", Version = "1.0.12", Source = "Repository", Repository = "CRAN", 
        Requirements = c("methods", "utils"), Hash = "5ea2700d21e038ace58269ecdbeb9ec0"), tinytex = list(Package = "tinytex", Version = "0.51", Source = "Repository", Repository = "CRAN", Requirements = "xfun", Hash = "d44e2fcd2e4e076f0aac540208559d1d"), blob = list(Package = "blob", Version = "1.2.4", Source = "Repository", Repository = "CRAN", Requirements = c("methods", "rlang", "vctrs"), Hash = "40415719b5a479b87949f3aa0aee737c"), sourcetools = list(Package = "sourcetools", Version = "0.1.7-1", 
        Source = "Repository", Repository = "CRAN", Requirements = "R", Hash = "5f5a7629f956619d519205ec475fe647"), later = list(Package = "later", Version = "1.3.2", Source = "Repository", Repository = "CRAN", Requirements = c("Rcpp", "rlang"), Hash = "a3e051d405326b8b0012377434c62b37"), jquerylib = list(Package = "jquerylib", Version = "0.1.4", Source = "Repository", Repository = "CRAN", Requirements = "htmltools", Hash = "5aab57a3bd297eee1c1d862735972182"), yaml = list(Package = "yaml", Version = "2.3.8", 
        Source = "Repository", Repository = "CRAN", Hash = "29240487a071f535f5e5d5a323b7afbd"), fastmap = list(Package = "fastmap", Version = "1.1.1", Source = "Repository", Repository = "CRAN", Hash = "f7736a18de97dea803bde0a2daaafb27"), mime = list(Package = "mime", Version = "0.12", Source = "Repository", Repository = "CRAN", Requirements = "tools", Hash = "18e9c28c1d3ca1560ce30658b22ce104"), R6 = list(Package = "R6", Version = "2.5.1", Source = "Repository", Repository = "CRAN", Requirements = "R", 
        Hash = "470851b6d5d0ac559e9d01bb352b4021"), shinymgr = list(Package = "shinymgr", Version = "1.1.0", Source = "Repository", Repository = "CRAN", Requirements = c("DBI", "R", "RSQLite", "reactable", "renv", "shiny", "shinydashboard", "shinyjs"), Hash = "bd41ca52731064ab5fdba39934f91808"), commonmark = list(Package = "commonmark", Version = "1.9.1", Source = "Repository", Repository = "CRAN", Hash = "5d8225445acb167abf7797de48b2ee3c"), shinyjs = list(Package = "shinyjs", Version = "2.1.0", 
        Source = "Repository", Repository = "CRAN", Requirements = c("R", "digest", "jsonlite", "shiny"), Hash = "802e4786b353a4bb27116957558548d5"), knitr = list(Package = "knitr", Version = "1.46", Source = "Repository", Repository = "CRAN", Requirements = c("R", "evaluate", "highr", "methods", "tools", "xfun", "yaml"), Hash = "6e008ab1d696a5283c79765fa7b56b47"), htmlwidgets = list(Package = "htmlwidgets", Version = "1.6.4", Source = "Repository", Repository = "CRAN", Requirements = c("grDevices", 
    "htmltools", "jsonlite", "knitr", "rmarkdown", "yaml"), Hash = "04291cc45198225444a397606810ac37"), reactable = list(Package = "reactable", Version = "0.4.4", Source = "Repository", Repository = "CRAN", Requirements = c("R", "digest", "htmltools", "htmlwidgets", "jsonlite", "reactR"), Hash = "6069eb2a6597963eae0605c1875ff14c"), shiny = list(Package = "shiny", Version = "1.8.1.1", Source = "Repository", Repository = "CRAN", Requirements = c("R", "R6", "bslib", "cachem", "commonmark", "crayon", 
    "fastmap", "fontawesome", "glue", "grDevices", "htmltools", "httpuv", "jsonlite", "later", "lifecycle", "methods", "mime", "promises", "rlang", "sourcetools", "tools", "utils", "withr", "xtable"), Hash = "54b26646816af9960a4c64d8ceec75d6"), DBI = list(Package = "DBI", Version = "1.2.2", Source = "Repository", Repository = "CRAN", Requirements = c("R", "methods"), Hash = "164809cd72e1d5160b4cb3aa57f510fe"), bslib = list(Package = "bslib", Version = "0.7.0", Source = "Repository", Repository = "CRAN", 
        Requirements = c("R", "base64enc", "cachem", "fastmap", "grDevices", "htmltools", "jquerylib", "jsonlite", "lifecycle", "memoise", "mime", "rlang", "sass"), Hash = "8644cc53f43828f19133548195d7e59e"), rlang = list(Package = "rlang", Version = "1.1.3", Source = "Repository", Repository = "CRAN", Requirements = c("R", "utils"), Hash = "42548638fae05fd9a9b5f3f437fbbbe2"), cachem = list(Package = "cachem", Version = "1.0.8", Source = "Repository", Repository = "CRAN", Requirements = c("fastmap", 
    "rlang"), Hash = "c35768291560ce302c0a6589f92e837d"), reactR = list(Package = "reactR", Version = "0.5.0", Source = "Repository", Repository = "CRAN", Requirements = "htmltools", Hash = "c9014fd1a435b2d790dd506589cb24e5"), httpuv = list(Package = "httpuv", Version = "1.6.15", Source = "Repository", Repository = "CRAN", Requirements = c("R", "R6", "Rcpp", "later", "promises", "utils"), Hash = "d55aa087c47a63ead0f6fc10f8fa1ee0"), xfun = list(Package = "xfun", Version = "0.43", Source = "Repository", 
        Repository = "CRAN", Requirements = c("grDevices", "stats", "tools"), Hash = "ab6371d8653ce5f2f9290f4ec7b42a8e"), fs = list(Package = "fs", Version = "1.6.4", Source = "Repository", Repository = "CRAN", Requirements = c("R", "methods"), Hash = "15aeb8c27f5ea5161f9f6a641fafd93a"), sass = list(Package = "sass", Version = "0.4.9", Source = "Repository", Repository = "CRAN", Requirements = c("R6", "fs", "htmltools", "rappdirs", "rlang"), Hash = "d53dbfddf695303ea4ad66f86e99b95d"), bit64 = list(
        Package = "bit64", Version = "4.0.5", Source = "Repository", Repository = "CRAN", Requirements = c("R", "bit", "methods", "stats", "utils"), Hash = "9fe98599ca456d6552421db0d6772d8f"), RSQLite = list(Package = "RSQLite", Version = "2.3.6", Source = "Repository", Repository = "CRAN", Requirements = c("DBI", "R", "bit64", "blob", "cpp11", "memoise", "methods", "pkgconfig", "plogr", "rlang"), Hash = "ae4a925e0f6bb1b7e5fa96b739c5221a"), memoise = list(Package = "memoise", Version = "2.0.1", Source = "Repository", 
        Repository = "CRAN", Requirements = c("cachem", "rlang"), Hash = "e2817ccf4a065c5d9d7f2cfbe7c1d78c"), cli = list(Package = "cli", Version = "3.6.2", Source = "Repository", Repository = "CRAN", Requirements = c("R", "utils"), Hash = "1216ac65ac55ec0058a6f75d7ca0fd52"), withr = list(Package = "withr", Version = "3.0.0", Source = "Repository", Repository = "CRAN", Requirements = c("R", "grDevices", "graphics"), Hash = "d31b6c62c10dcf11ec530ca6b0dd5d35"), magrittr = list(Package = "magrittr", 
        Version = "2.0.3", Source = "Repository", Repository = "CRAN", Requirements = "R", Hash = "7ce2733a9826b3aeb1775d56fd305472"), digest = list(Package = "digest", Version = "0.6.35", Source = "Repository", Repository = "CRAN", Requirements = c("R", "utils"), Hash = "698ece7ba5a4fa4559e3d537e7ec3d31"), fontawesome = list(Package = "fontawesome", Version = "0.5.2", Source = "Repository", Repository = "CRAN", Requirements = c("R", "htmltools", "rlang"), Hash = "c2efdd5f0bcd1ea861c2d4e2a883a67d"), 
    xtable = list(Package = "xtable", Version = "1.8-4", Source = "Repository", Repository = "CRAN", Requirements = c("R", "stats", "utils"), Hash = "b8acdf8af494d9ec19ccb2481a9b11c2"), base64enc = list(Package = "base64enc", Version = "0.1-3", Source = "Repository", Repository = "CRAN", Requirements = "R", Hash = "543776ae6848fde2f48ff3816d0628bc"), rappdirs = list(Package = "rappdirs", Version = "0.3.3", Source = "Repository", Repository = "CRAN", Requirements = "R", Hash = "5e3c5dc0b071b21fa128676560dbe94d"), 
    lifecycle = list(Package = "lifecycle", Version = "1.0.4", Source = "Repository", Repository = "CRAN", Requirements = c("R", "cli", "glue", "rlang"), Hash = "b8552d117e1b808b09a832f589b79035"), vctrs = list(Package = "vctrs", Version = "0.6.5", Source = "Repository", Repository = "CRAN", Requirements = c("R", "cli", "glue", "lifecycle", "rlang"), Hash = "c03fa420630029418f7e6da3667aac4a"), evaluate = list(Package = "evaluate", Version = "0.23", Source = "Repository", Repository = "CRAN", Requirements = c("R", 
    "methods"), Hash = "daf4a1246be12c1fa8c7705a0935c1a0"), glue = list(Package = "glue", Version = "1.7.0", Source = "Repository", Repository = "CRAN", Requirements = c("R", "methods"), Hash = "e0b3a53876554bd45879e596cdb10a52"), plogr = list(Package = "plogr", Version = "0.2.0", Source = "Repository", Repository = "CRAN", Hash = "09eb987710984fc2905c7129c7d85e65"), rmarkdown = list(Package = "rmarkdown", Version = "2.26", Source = "Repository", Repository = "CRAN", Requirements = c("R", "bslib", 
    "evaluate", "fontawesome", "htmltools", "jquerylib", "jsonlite", "knitr", "methods", "tinytex", "tools", "utils", "xfun", "yaml"), Hash = "9b148e7f95d33aac01f31282d49e4f44"), pkgconfig = list(Package = "pkgconfig", Version = "2.0.3", Source = "Repository", Repository = "CRAN", Requirements = "utils", Hash = "01f28d4278f15c76cddbea05899c5d6f"), htmltools = list(Package = "htmltools", Version = "0.5.8.1", Source = "Repository", Repository = "CRAN", Requirements = c("R", "base64enc", "digest", "fastmap", 
    "grDevices", "rlang", "utils"), Hash = "81d371a9cc60640e74e4ab6ac46dcedc")))
      )
    )
    observeEvent(input$next_tab_1, {
      shinyjs::js$enableTab('tab2')
      shinyjs::js$disableTab('tab1')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab2'
      )
    })
    observeEvent(input$previous_tab_2, {
      shinyjs::delay(50, {
        shinyjs::js$enableTab('tab1')
        shinyjs::js$disableTab('tab2')
      })
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab1'
      )
    })
  })
}
