# This script was automatically generated by the shinymgr (vers. 1.1.0) R package's App Builder on 2025-05-30 13:46:51.864272.
# For more information, visit: https://code.usgs.gov/vtcfwru/shinymgr

library(AMMonitor)
library(DBI)
library(htmltools)
library(reactable)
library(shinyjs)

jscode <- "
shinyjs.disableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.bind('click.tab', function(e) {
e.preventDefault();
return false;
});
tab.addClass('disabled');
}

shinyjs.enableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.unbind('click.tab');
tab.removeClass('disabled');
}
"

css <- "
.nav li a.disabled {
background-color: #bbb !important;
border-color: #ccc !important;
cursor: not-allowed !important;
}"


equipManager_ui <- function(id) {
  ns <- NS(id)
  tagList(
    fluidPage(
      shinyjs::useShinyjs(),
      shinyjs::extendShinyjs(text = jscode, functions = c('disableTab','enableTab')),
      shinyjs::inlineCSS(css),
      actionButton(
        ns("start"),
        "Start New Analysis",
        onclick = "var $btn=$(this); setTimeout(function(){$btn.remove();},0);"
      ),
      uiOutput(ns('appUI'))
    )
  )
}
equipManager_server <- function(id, userID, shinyMgrPath) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns
    observeEvent(input$start, {

      shinyjs::disable('start')

      output$appUI <- renderUI({
        tagList(
          tabsetPanel(
            id = ns("mainTabSet"),
            tabPanel(
              "Add Equipment Models", 
              value = "tab1",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                HTML("Monitoring equipment comes in many different makes and models, each with their own features and settings. Several tables in the AMMonitor database store metadata related to equipment models, settings, and configurations, and this app helps populate these tables.<br><br> Use the left pane, \"Add New Equipment Models\", to add new equipment models to the database.<br><br> Use the right pane, \"Model Settings\", to add settings by first select an equipment model for which you want to add/edit/delete setting options. Next, you can create a setting. After adding a setting, it will appear in a table below. If the setting has categorical options (e.g., a \"brightness\" setting for a trail camera with options \"low\" and \"high\"), you can add those options by clicking the \"plus\" sign to the right of the option name. Any setings without options will accept numerical values. <br><br> Advance to the next tab to add model configurations.")
              ),
              equipManager_add_settings_ui(ns("mod1")),
              fluidRow(
                actionButton(ns('next_tab_1'), label = "Next")
              )
            ),
            tabPanel(
              "Add Configurations", 
              value = "tab2",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                "Equipment configurations define which settings were used during data collection and are linked to media files through the \"visits\" table. This tab allows you to create new equipment configurations. To start, select the equipment model. Next, name and describe your configuration (e.g., the \"Moose study 2025\" configuration). Finally, you can select the equipment setting options that were used during data collection. Once added, configurations can be modified or removed using the table below."
              ),
              equipManager_add_configurations_ui(ns("mod2")),
              fluidRow(
                actionButton(ns('previous_tab_2'), label = "Previous")
              )
            )
          ),
          tags$p(tags$i("App created with shinymgr"), style = "text-align:right")
        )
      })
      shinyjs::delay(50, {
        shinyjs::js$disableTab("tab2")
        shinyjs::js$disableTab("tab3")
      })
    })

    data1 <- equipManager_add_settings_server("mod1")
    equipManager_add_configurations_server("mod2", update_equip_models = data1$update_equip_models)
    observeEvent(input$next_tab_1, {
      shinyjs::js$enableTab('tab2')
      shinyjs::js$disableTab('tab1')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab2'
      )
    })
    observeEvent(input$previous_tab_2, {
      shinyjs::delay(50, {
        shinyjs::js$enableTab('tab1')
        shinyjs::js$disableTab('tab2')
      })
      removeTab('mainTabSet','tab2',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Add Configurations",
          value = "tab2",
          equipManager_add_configurations_ui(ns("mod2")),
          fluidRow(
            actionButton(ns('previous_tab_2'), label = "Previous")
          )
        ),
        target = 'tab1',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab1'
      )
    })
  })
}
