# This script was automatically generated by the shinymgr (vers. 1.1.0) R package's App Builder on 2025-06-03 12:09:48.870141.
# For more information, visit: https://code.usgs.gov/vtcfwru/shinymgr

library(AMMonitor)
library(DBI)
library(htmltools)
library(reactable)
library(shinyjs)

jscode <- "
shinyjs.disableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.bind('click.tab', function(e) {
e.preventDefault();
return false;
});
tab.addClass('disabled');
}

shinyjs.enableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.unbind('click.tab');
tab.removeClass('disabled');
}
"

css <- "
.nav li a.disabled {
background-color: #bbb !important;
border-color: #ccc !important;
cursor: not-allowed !important;
}"


modelManager_ui <- function(id) {
  ns <- NS(id)
  tagList(
    fluidPage(
      shinyjs::useShinyjs(),
      shinyjs::extendShinyjs(text = jscode, functions = c('disableTab','enableTab')),
      shinyjs::inlineCSS(css),
      actionButton(
        ns("start"),
        "Start New Analysis",
        onclick = "var $btn=$(this); setTimeout(function(){$btn.remove();},0);"
      ),
      uiOutput(ns('appUI'))
    )
  )
}
modelManager_server <- function(id, userID, shinyMgrPath) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns
    observeEvent(input$start, {

      shinyjs::disable('start')

      output$appUI <- renderUI({
        tagList(
          tabsetPanel(
            id = ns("mainTabSet"),
            tabPanel(
              "Model and Model Settings", 
              value = "tab1",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                HTML("Machine Learning (ML) Models can be used to automate detection of wildlife signals from media data. Several tables in the AMMonitor database store metadata related to ML models, settings, and configurations, and this app helps populate these tables.<br><br> Use the left side of this page, \"Add New (Machine Learning) Models\", to add new ML models to the database. You can specify if the model pertains to a particular taxon (or list of taxa), however any taxon lists will need to be created in the database in advance. <br><br> Use the right pane, \"Model Settings\", to add settings by first selecting an ML model for which you want to add/edit/delete setting options. Next, you can create a setting. After adding a setting, it will appear in a table below. If the setting has categorical options, you can add those options by clicking the \"plus\" sign to the right of the option name. Any setings without options will accept numerical values. <br><br> Advance to the next tab to add model configurations.")
              ),
              modelManager_add_settings_ui(ns("mod1")),
              fluidRow(
                actionButton(ns('next_tab_1'), label = "Next")
              )
            ),
            tabPanel(
              "Model Congifurations", 
              value = "tab2",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                "Model configurations allow you to track which model settings were used in an analysis. They can be associated with model outputs (form the modeloutputs table). Add, edit, and delete model configurations here."
              ),
              modelManager_add_configurations_ui(ns("mod2")),
              fluidRow(
                actionButton(ns('previous_tab_2'), label = "Previous")
              )
            )
          ),
          tags$p(tags$i("App created with shinymgr"), style = "text-align:right")
        )
      })
      shinyjs::delay(50, {
        shinyjs::js$disableTab("tab2")
        shinyjs::js$disableTab("tab3")
      })
    })

    data1 <- modelManager_add_settings_server("mod1")
    modelManager_add_configurations_server("mod2", update_models = data1$update_models)
    observeEvent(input$next_tab_1, {
      shinyjs::js$enableTab('tab2')
      shinyjs::js$disableTab('tab1')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab2'
      )
    })
    observeEvent(input$previous_tab_2, {
      shinyjs::delay(50, {
        shinyjs::js$enableTab('tab1')
        shinyjs::js$disableTab('tab2')
      })
      removeTab('mainTabSet','tab2',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Model Congifurations",
          value = "tab2",
          modelManager_add_configurations_ui(ns("mod2")),
          fluidRow(
            actionButton(ns('previous_tab_2'), label = "Previous")
          )
        ),
        target = 'tab1',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab1'
      )
    })
  })
}
