# This script was automatically generated by the shinymgr (vers. 1.0.0) R package's App Builder on 2023-06-19 16:51:20.874835.
# For more information, visit: https://code.usgs.gov/vtcfwru/shinymgr

library(DBI)
library(reactable)
library(shinyFiles)
library(tools)

jscode <- "
shinyjs.disableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.bind('click.tab', function(e) {
e.preventDefault();
return false;
});
tab.addClass('disabled');
}

shinyjs.enableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.unbind('click.tab');
tab.removeClass('disabled');
}
"

css <- "
.nav li a.disabled {
background-color: #bbb !important;
border-color: #ccc !important;
cursor: not-allowed !important;
}"


registerVisit_ui <- function(id) {
  ns <- NS(id)
  tagList(
    fluidPage(
      useShinyjs(),
      extendShinyjs(text = jscode, functions = c('disableTab','enableTab')),
      inlineCSS(css),
      actionButton(
        ns("start"),
        "Start New Analysis",
        onclick = "var $btn=$(this); setTimeout(function(){$btn.remove();},0);"
      ),
      uiOutput(ns('appUI'))
    )
  )
}
registerVisit_server <- function(id, userID, shinyMgrPath) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns
    observeEvent(input$start, {

      disable('start')

      output$appUI <- renderUI({
        tagList(
          tabsetPanel(
            id = ns("mainTabSet"),
            tabPanel(
              "Intro", 
              value = "tab1",
              tags$br(),
              registerVisitIntro_ui(ns("mod1")),
              fluidRow(
                actionButton(ns('next_tab_1'), label = "Next")
              )
            ),
            tabPanel(
              "Select Media Type", 
              value = "tab2",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                'Select the media type ("photos" for cameras or "recordings" for audio recorders). Only one media type can be registered at a time.'
              ),
              registerVisitMediaType_ui(ns("mod2")),
              fluidRow(
                actionButton(ns('previous_tab_2'), label = "Previous"),
                actionButton(ns('next_tab_2'), label = "Next")
              )
            ),
            tabPanel(
              "Enter Metadata", 
              value = "tab3",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                "Enter site visit metadata here. Core fields include the visit location, date, time, the ID of the quipment being visited, person who conducted the visit, and the visit type. Hover your mouse over the \"visit type\" field for a short definition of each type. Additional fields, including any user fields, are shown below, along with their definitions."
              ),
              registerVisitMetadata_ui(ns("mod3")),
              fluidRow(
                actionButton(ns('previous_tab_3'), label = "Previous"),
                actionButton(ns('next_tab_3'), label = "Next")
              )
            ),
            tabPanel(
              "Media Upload", 
              value = "tab4",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                "If there are media files associated the visit, you can specify the file path to the directory containing these media files. You can also select a destination where these files will be saved after being registered in your database (defaulting to the \"photos/recordings\" folder of your AMMonitor project directory). If there are no files to register, you may proceed by clicking \"Next\" below without specifying a media source/destination."
              ),
              registerVisitSetSourceDest_ui(ns("mod4")),
              fluidRow(
                actionButton(ns('previous_tab_4'), label = "Previous"),
                actionButton(ns('next_tab_4'), label = "Next")
              )
            ),
            tabPanel(
              "Check Visit", 
              value = "tab5",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                "Click the \"Generate warnings\" button to screen your visit for potential issues. A table is generated listing the warnings, their severity, and possible action items for resolving each issue. Check the \"Create a log\" box for a csv log file to be created based on any warnings and associated with the visit."
              ),
              registerVisitMediaCheck_ui(ns("mod5")),
              fluidRow(
                actionButton(ns('previous_tab_5'), label = "Previous"),
                actionButton(ns('next_tab_5'), label = "Next")
              )
            ),
            tabPanel(
              "Register Visit", 
              value = "tab6",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                "Specify the file naming format for all new media files. Press the \"Add the new visit\" button to register the visit, logs, and any associated media files in your database. After a visit is successfully registered in your database, any added visits and media files will be immediately visible in the \"Database\" portal."
              ),
              registerVisitUpdateDB_ui(ns("mod6")),
              fluidRow(
                actionButton(ns('previous_tab_6'), label = "Previous"),
                actionButton(ns('next_tab_6'), label = "Next")
              )
            ),
            tabPanel(
              "Save",
              value = "tab7",
              save_analysis_ui(ns("mod7")),
              tags$br(),
              tags$br(),
              fluidRow(
                actionButton(ns("previous_tab_7"), label = "Previous")
              )
            )
          ),
          tags$p(tags$i("App created with shinymgr"), style = "text-align:right")
        )
      })
      delay(50, {
        js$disableTab("tab2")
        js$disableTab("tab3")
        js$disableTab("tab4")
        js$disableTab("tab5")
        js$disableTab("tab6")
        js$disableTab("tab7")
      })
    })

    registerVisitIntro_server("mod1")
    data1 <- registerVisitMediaType_server("mod2")
    data2 <- registerVisitMetadata_server("mod3", mediaType = data1$mediaType)
    data3 <- registerVisitSetSourceDest_server("mod4", mediaType = data1$mediaType)
    data4 <- registerVisitMediaCheck_server("mod5", mediaType = data1$mediaType, visitMetadata = data2$visitMetadata, selectedFiles = data3$selectedFiles, audio_fn_format = data3$audio_fn_format)
    data5 <- registerVisitUpdateDB_server("mod6", mediaType = data1$mediaType, visitMetadata = data2$visitMetadata, screenData = data4$screenData, filePaths = data3$selectedFiles, data3$dirDest, storage_type = data3$storage_type, includeLogFile = data4$includeLogFile)
    save_analysis_server("mod7",
      appName = "registerVisit",
      moduleInput = input,
      returns = list(
        data1 = list(
          mediaType = data1$mediaType()
        ),
        data2 = list(
          visitMetadata = data2$visitMetadata()
        ),
        data3 = list(
          selectedFiles = data3$selectedFiles(),
          dirDest = data3$dirDest()
        ),
        data4 = list(
          screenData = data4$screenData(),
          includeLogFile = data4$includeLogFile()
        ),
        data5 = list(
          status = data5$status(),
          newVisit = data5$newVisit()
        )
      ),
      metadata = list(
        appDescription = "test",
        mod1 = list(
          dataset = "no returns",
          modName = "registerVisitIntro",
          modDisplayName = "visit_registration_intro",
          modDescription = "Intro / Instructions to the UI approach to registering a visit",
          modArguments = "This module has no additional arguments",
          modReturns = "This module has no returns",
          modPackages = "This module has no package dependencies"
        ),
        mod2 = list(
          dataset = "data1",
          modName = "registerVisitMediaType",
          modDisplayName = "Media Type",
          modDescription = "Select a media type from photo/recording/video.",
          modArguments = "This module has no additional arguments",
          modReturns = data.frame(
            name = c("mediaType"),
            class = c("Character"),
            description = c("Media Type")
          ),
          modPackages = "This module has no package dependencies"
        ),
        mod3 = list(
          dataset = "data2",
          modName = "registerVisitMetadata",
          modDisplayName = "Enter Visit MetaData",
          modDescription = "Visit metadata entered here, associated with media registration.",
          modArguments = data.frame(
            name = c("mediaType"),
            class = c("Character"),
            description = c("Media Type (photos/recordings/videos)")
          ),
          modReturns = data.frame(
            name = c("visitMetadata"),
            class = c("returnClass"),
            description = c("returnDescription")
          ),
          modPackages = data.frame(
            name = c("DBI"),
            version = c("1.1.3")
          )
        ),
        mod4 = list(
          dataset = "data3",
          modName = "registerVisitSetSourceDest",
          modDisplayName = "Select source and destination for media files to register.",
          modDescription = "The user selects source and destination directories.",
          modArguments = data.frame(
            name = c("mediaType"),
            class = c("Character"),
            description = c("Media type (photos/recordings/videos)")
          ),
          modReturns = data.frame(
            name = c("selectedFiles","dirDest"),
            class = c("Character","Character"),
            description = c("File paths for media to be registered","File path to destination directory")
          ),
          modPackages = data.frame(
            name = c("shinyFiles","tools"),
            version = c("0.9.3","4.3.0")
          )
        ),
        mod5 = list(
          dataset = "data4",
          modName = "registerVisitMediaCheck",
          modDisplayName = "Check Media Files",
          modDescription = "Check media files for any potential issues",
          modArguments = data.frame(
            name = c("mediaType","visitMetaData","selectedFiles"),
            class = c("character","data.frame","Character"),
            description = c("Media type (photos/recordings/videos)","Metadata for the new visit record","File paths for media to be registered")
          ),
          modReturns = data.frame(
            name = c("screenData","includeLogFile"),
            class = c("list","logical"),
            description = c("status, warnings, and exif data","Whether to add a log file")
          ),
          modPackages = data.frame(
            name = c("reactable"),
            version = c("0.3.0")
          )
        ),
        mod6 = list(
          dataset = "data5",
          modName = "registerVisitUpdateDB",
          modDisplayName = "Register a visit (and media) into the database.",
          modDescription = "Adds new row(s) to visits, photos/recordings/videos, and logs tables.",
          modArguments = data.frame(
            name = c("mediaType","visitMetadata","screenData","filePaths","includeLogFile"),
            class = c("character","data.frame","list","character","logical"),
            description = c("Type of media (photos/recordings/videos)","Values of each column for the new row in visits table","Data returned by screening function (including exif data)","File paths to new media (photos/recordings/videos)","Data returned by screening function (including exif data)")
          ),
          modReturns = data.frame(
            name = c("status","newVisit"),
            class = c("logical","data.frame"),
            description = c("Whether the registration was a success","The new row that was added to the visit table")
          ),
          modPackages = "This module has no package dependencies"
        ),
        lockfile = list(R = list(Version = "4.3.0", Repositories = list(CRAN = "https://cran.rstudio.com/")), Packages = list(shinydashboard = list(Package = "shinydashboard", Version = "0.7.2", Source = "Repository", Depends = "R (>= 3.0)", Imports = c("utils", "shiny (>= 1.0.0)", "htmltools (>= 0.2.6)", "promises"), Repository = "CRAN", Hash = "e418b532e9bb4eb22a714b9a9f1acee7"), bit = list(Package = "bit", Version = "4.0.4", Source = "Repository", Depends = "R (>= 2.9.2)", Repository = "CRAN", Hash = "f36715f14d94678eea9933af927bc15d"), jsonlite = list(Package = "jsonlite", Version = "1.8.4", Source = "Repository", 
    Depends = "methods", Repository = "CRAN", Hash = "a4269a09a9b865579b2635c77e572374"), renv = list(Package = "renv", Version = "0.15.5", Source = "Repository", Imports = "utils", Repository = "CRAN", Hash = "6a38294e7d12f5d8e656b08c5bd8ae34"), crayon = list(Package = "crayon", Version = "1.5.2", Source = "Repository", Imports = c("grDevices", "methods", "utils"), Repository = "CRAN", Hash = "e8a1e41acf02548751f45c718d55aa6a"), promises = list(Package = "promises", Version = "1.2.0.1", Source = "Repository", 
    Imports = c("R6", "Rcpp", "later", "rlang", "stats", "magrittr"), LinkingTo = c("later", "Rcpp"), Repository = "CRAN", Hash = "4ab2c43adb4d4699cf3690acd378d75d"), Rcpp = list(Package = "Rcpp", Version = "1.0.9", Source = "Repository", Imports = c("methods", "utils"), Repository = "CRAN", Hash = "e9c08b94391e9f3f97355841229124f2"), blob = list(Package = "blob", Version = "1.2.3", Source = "Repository", Imports = c("methods", "rlang", "vctrs (>= 0.2.1)"), Repository = "CRAN", Hash = "10d231579bc9c06ab1c320618808d4ff"), 
    sourcetools = list(Package = "sourcetools", Version = "0.1.7", Source = "Repository", Depends = "R (>= 3.0.2)", Repository = "CRAN", Hash = "947e4e02a79effa5d512473e10f41797"), later = list(Package = "later", Version = "1.3.0", Source = "Repository", Imports = c("Rcpp (>= 0.12.9)", "rlang"), LinkingTo = "Rcpp", Repository = "CRAN", Hash = "7e7b457d7766bc47f2a5f21cc2984f8e"), jquerylib = list(Package = "jquerylib", Version = "0.1.4", Source = "Repository", Imports = "htmltools", Repository = "CRAN", 
        Hash = "5aab57a3bd297eee1c1d862735972182"), yaml = list(Package = "yaml", Version = "2.3.5", Source = "Repository", Repository = "CRAN", Hash = "458bb38374d73bf83b1bb85e353da200"), fastmap = list(Package = "fastmap", Version = "1.1.0", Source = "Repository", Repository = "CRAN", Hash = "77bd60a6157420d4ffa93b27cf6a58b8"), mime = list(Package = "mime", Version = "0.12", Source = "Repository", Imports = "tools", Repository = "CRAN", Hash = "18e9c28c1d3ca1560ce30658b22ce104"), shinymgr = list(
        Package = "shinymgr", Version = "1.0.0", Source = "unknown", Depends = c("R (>= 3.5.0)", "DBI", "reactable", "renv", "RSQLite", "shiny", "shinyjs", "shinydashboard"), Hash = "83de17c2f960356211dfc80b4f6d633c"), R6 = list(Package = "R6", Version = "2.5.1", Source = "Repository", Depends = "R (>= 3.0)", Repository = "CRAN", Hash = "470851b6d5d0ac559e9d01bb352b4021"), shinyjs = list(Package = "shinyjs", Version = "2.1.0", Source = "Repository", Depends = "R (>= 3.1.0)", Imports = c("digest (>= 0.6.8)", 
    "jsonlite", "shiny (>= 1.0.0)"), Repository = "CRAN", Hash = "802e4786b353a4bb27116957558548d5"), commonmark = list(Package = "commonmark", Version = "1.8.0", Source = "Repository", Repository = "CRAN", Hash = "2ba81b120c1655ab696c935ef33ea716"), htmlwidgets = list(Package = "htmlwidgets", Version = "1.5.4", Source = "Repository", Imports = c("grDevices", "htmltools (>= 0.3)", "jsonlite (>= 0.9.16)", "yaml"), Repository = "CRAN", Hash = "76147821cd3fcd8c4b04e1ef0498e7fb"), shinyFiles = list(Package = "shinyFiles", 
        Version = "0.9.3", Source = "Repository", Imports = c("htmltools", "jsonlite", "tools", "shiny (>= 1.1.0)", "fs (>= 1.2.6)", "tibble (>= 1.4.2)"), Repository = "CRAN", Hash = "92c28bcdee44e205a99799f6ea604b82"), tibble = list(Package = "tibble", Version = "3.1.8", Source = "Repository", Depends = "R (>= 3.1.0)", Imports = c("fansi (>= 0.4.0)", "lifecycle (>= 1.0.0)", "magrittr", "methods", "pillar (>= 1.7.0)", "pkgconfig", "rlang (>= 1.0.2)", "utils", "vctrs (>= 0.3.8)"), Repository = "CRAN", 
        Hash = "56b6934ef0f8c68225949a8672fe1a8f"), reactable = list(Package = "reactable", Version = "0.3.0", Source = "Repository", Depends = "R (>= 3.1)", Imports = c("digest", "htmltools", "htmlwidgets", "jsonlite", "reactR"), Repository = "CRAN", Hash = "377c52754f3e6c17673c79740e9296d7"), shiny = list(Package = "shiny", Version = "1.7.3", Source = "Repository", Depends = c("R (>= 3.0.2)", "methods"), Imports = c("utils", "grDevices", "httpuv (>= 1.5.2)", "mime (>= 0.3)", "jsonlite (>= 0.9.16)", 
    "xtable", "fontawesome (>= 0.4.0)", "htmltools (>= 0.5.2)", "R6 (>= 2.0)", "sourcetools", "later (>= 1.0.0)", "promises (>= 1.1.0)", "tools", "crayon", "rlang (>= 0.4.10)", "fastmap (>= 1.1.0)", "withr", "commonmark (>= 1.7)", "glue (>= 1.3.2)", "bslib (>= 0.3.0)", "cachem", "ellipsis", "lifecycle (>= 0.2.0)"), Repository = "CRAN", Hash = "fe12df67fdb3b1142325cc54f100cc06"), DBI = list(Package = "DBI", Version = "1.1.3", Source = "Repository", Depends = c("methods", "R (>= 3.0.0)"), Repository = "CRAN", 
        Hash = "b2866e62bab9378c3cc9476a1954226b"), bslib = list(Package = "bslib", Version = "0.4.0", Source = "Repository", Depends = "R (>= 2.10)", Imports = c("grDevices", "htmltools (>= 0.5.2)", "jsonlite", "sass (>= 0.4.0)", "jquerylib (>= 0.1.3)", "rlang", "cachem", "memoise"), Repository = "CRAN", Hash = "be5ee090716ce1671be6cd5d7c34d091"), pillar = list(Package = "pillar", Version = "1.8.1", Source = "Repository", Imports = c("cli (>= 2.3.0)", "fansi", "glue", "lifecycle", "rlang (>= 1.0.2)", 
    "utf8 (>= 1.1.0)", "utils", "vctrs (>= 0.3.8)"), Repository = "CRAN", Hash = "f2316df30902c81729ae9de95ad5a608"), rlang = list(Package = "rlang", Version = "1.0.6", Source = "Repository", Depends = "R (>= 3.4.0)", Imports = "utils", Repository = "CRAN", Hash = "4ed1f8336c8d52c3e750adcdc57228a7"), utf8 = list(Package = "utf8", Version = "1.2.2", Source = "Repository", Depends = "R (>= 2.10)", Repository = "CRAN", Hash = "c9c462b759a5cc844ae25b5942654d13"), cachem = list(Package = "cachem", Version = "1.0.6", 
        Source = "Repository", Imports = c("rlang", "fastmap"), Repository = "CRAN", Hash = "648c5b3d71e6a37e3043617489a0a0e9"), reactR = list(Package = "reactR", Version = "0.4.4", Source = "Repository", Imports = "htmltools", Repository = "CRAN", Hash = "75389c8091eb14ee21c6bc87a88b3809"), httpuv = list(Package = "httpuv", Version = "1.6.11", Source = "Repository", Depends = "R (>= 2.15.1)", Imports = c("Rcpp (>= 1.0.7)", "utils", "R6", "promises", "later (>= 0.8.0)"), LinkingTo = c("Rcpp", "later"
    ), Repository = "CRAN", Hash = "838602f54e32c1a0f8cc80708cefcefa"), fs = list(Package = "fs", Version = "1.5.2", Source = "Repository", Depends = "R (>= 3.1)", Imports = "methods", Repository = "CRAN", Hash = "7c89603d81793f0d5486d91ab1fc6f1d"), sass = list(Package = "sass", Version = "0.4.2", Source = "Repository", Imports = c("fs", "rlang (>= 0.4.10)", "htmltools (>= 0.5.1)", "R6", "rappdirs"), Repository = "CRAN", Hash = "1b191143d7d3444d504277843f3a95fe"), bit64 = list(Package = "bit64", 
        Version = "4.0.5", Source = "Repository", Depends = c("R (>= 3.0.1)", "bit (>= 4.0.0)", "utils", "methods", "stats"), Repository = "CRAN", Hash = "9fe98599ca456d6552421db0d6772d8f"), RSQLite = list(Package = "RSQLite", Version = "2.2.14", Source = "Repository", Depends = "R (>= 3.1.0)", Imports = c("bit64", "blob (>= 1.2.0)", "DBI (>= 1.1.0)", "memoise", "methods", "pkgconfig", "Rcpp (>= 1.0.7)"), LinkingTo = c("plogr (>= 0.2.0)", "Rcpp"), Repository = "CRAN", Hash = "086113da6af75461b8dc8d916dcf9620"), 
    memoise = list(Package = "memoise", Version = "2.0.1", Source = "Repository", Imports = c("rlang (>= 0.4.10)", "cachem"), Repository = "CRAN", Hash = "e2817ccf4a065c5d9d7f2cfbe7c1d78c"), cli = list(Package = "cli", Version = "3.6.0", Source = "Repository", Depends = "R (>= 3.4)", Imports = "utils", Repository = "CRAN", Hash = "3177a5a16c243adc199ba33117bd9657"), withr = list(Package = "withr", Version = "2.5.0", Source = "Repository", Depends = "R (>= 3.2.0)", Imports = c("graphics", "grDevices", 
    "stats"), Repository = "CRAN", Hash = "c0e49a9760983e81e55cdd9be92e7182"), magrittr = list(Package = "magrittr", Version = "2.0.3", Source = "Repository", Depends = "R (>= 3.4.0)", Repository = "CRAN", Hash = "7ce2733a9826b3aeb1775d56fd305472"), digest = list(Package = "digest", Version = "0.6.29", Source = "Repository", Depends = "R (>= 3.3.0)", Imports = "utils", Repository = "CRAN", Hash = "cf6b206a045a684728c3267ef7596190"), fontawesome = list(Package = "fontawesome", Version = "0.4.0", Source = "Repository", 
        Depends = "R (>= 3.3.0)", Imports = c("rlang (>= 0.4.10)", "htmltools (>= 0.5.1.1)"), Repository = "CRAN", Hash = "c5a628c2570aa86a96cc6ef739d8bfda"), xtable = list(Package = "xtable", Version = "1.8-4", Source = "Repository", Depends = "R (>= 2.10.0)", Imports = c("stats", "utils"), Repository = "CRAN", Hash = "b8acdf8af494d9ec19ccb2481a9b11c2"), base64enc = list(Package = "base64enc", Version = "0.1-3", Source = "Repository", Depends = "R (>= 2.9.0)", Repository = "CRAN", Hash = "543776ae6848fde2f48ff3816d0628bc"), 
    rappdirs = list(Package = "rappdirs", Version = "0.3.3", Source = "Repository", Depends = "R (>= 3.2)", Repository = "CRAN", Hash = "5e3c5dc0b071b21fa128676560dbe94d"), lifecycle = list(Package = "lifecycle", Version = "1.0.3", Source = "Repository", Depends = "R (>= 3.4)", Imports = c("cli (>= 3.4.0)", "glue", "rlang (>= 1.0.6)"), Repository = "CRAN", Hash = "001cecbeac1cff9301bdc3775ee46a86"), vctrs = list(Package = "vctrs", Version = "0.5.2", Source = "Repository", Depends = "R (>= 3.3)", 
        Imports = c("cli (>= 3.4.0)", "glue", "lifecycle (>= 1.0.3)", "rlang (>= 1.0.6)"), Repository = "CRAN", Hash = "e4ffa94ceed5f124d429a5a5f0f5b378"), glue = list(Package = "glue", Version = "1.6.2", Source = "Repository", Depends = "R (>= 3.4)", Imports = "methods", Repository = "CRAN", Hash = "4f2596dfb05dac67b9dc558e5c6fba2e"), plogr = list(Package = "plogr", Version = "0.2.0", Source = "Repository", Repository = "CRAN", Hash = "09eb987710984fc2905c7129c7d85e65"), fansi = list(Package = "fansi", 
        Version = "1.0.3", Source = "Repository", Depends = "R (>= 3.1.0)", Imports = c("grDevices", "utils"), Repository = "CRAN", Hash = "83a8afdbe71839506baa9f90eebad7ec"), pkgconfig = list(Package = "pkgconfig", Version = "2.0.3", Source = "Repository", Imports = "utils", Repository = "CRAN", Hash = "01f28d4278f15c76cddbea05899c5d6f"), ellipsis = list(Package = "ellipsis", Version = "0.3.2", Source = "Repository", Depends = "R (>= 3.2)", Imports = "rlang (>= 0.3.0)", Repository = "CRAN", Hash = "bb0eec2fe32e88d9e2836c2f73ea2077"), 
    htmltools = list(Package = "htmltools", Version = "0.5.2", Source = "Repository", Depends = "R (>= 2.14.1)", Imports = c("utils", "digest", "grDevices", "base64enc", "rlang (>= 0.4.10)", "fastmap"), Repository = "CRAN", Hash = "526c484233f42522278ab06fb185cb26")))
      )
    )
    observeEvent(input$next_tab_1, {
      js$enableTab('tab2')
      js$disableTab('tab1')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab2'
      )
    })
    observeEvent(input$next_tab_2, {
      js$enableTab('tab3')
      js$disableTab('tab2')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab3'
      )
    })
    observeEvent(input$previous_tab_2, {
      delay(50, {
        js$enableTab('tab1')
        js$disableTab('tab2')
      })
      removeTab('mainTabSet','tab2',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Select Media Type",
          value = "tab2",
          registerVisitMediaType_ui(ns("mod2")),
          fluidRow(
            actionButton(ns('previous_tab_2'), label = "Previous"),
            actionButton(ns('next_tab_2'), label = "Next")
          )
        ),
        target = 'tab1',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab1'
      )
    })
    observeEvent(input$next_tab_3, {
      js$enableTab('tab4')
      js$disableTab('tab3')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab4'
      )
    })
    observeEvent(input$previous_tab_3, {
      delay(50, {
        js$enableTab('tab2')
        js$disableTab('tab3')
      })
      removeTab('mainTabSet','tab3',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Enter Metadata",
          value = "tab3",
          registerVisitMetadata_ui(ns("mod3")),
          fluidRow(
            actionButton(ns('previous_tab_3'), label = "Previous"),
            actionButton(ns('next_tab_3'), label = "Next")
          )
        ),
        target = 'tab2',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab2'
      )
    })
    observeEvent(input$next_tab_4, {
      js$enableTab('tab5')
      js$disableTab('tab4')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab5'
      )
    })
    observeEvent(input$previous_tab_4, {
      delay(50, {
        js$enableTab('tab3')
        js$disableTab('tab4')
      })
      removeTab('mainTabSet','tab4',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Media Upload",
          value = "tab4",
          registerVisitSetSourceDest_ui(ns("mod4")),
          fluidRow(
            actionButton(ns('previous_tab_4'), label = "Previous"),
            actionButton(ns('next_tab_4'), label = "Next")
          )
        ),
        target = 'tab3',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab3'
      )
    })
    observeEvent(input$next_tab_5, {
      js$enableTab('tab6')
      js$disableTab('tab5')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab6'
      )
    })
    observeEvent(input$previous_tab_5, {
      delay(50, {
        js$enableTab('tab4')
        js$disableTab('tab5')
      })
      removeTab('mainTabSet','tab5',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Check Visit",
          value = "tab5",
          registerVisitMediaCheck_ui(ns("mod5")),
          fluidRow(
            actionButton(ns('previous_tab_5'), label = "Previous"),
            actionButton(ns('next_tab_5'), label = "Next")
          )
        ),
        target = 'tab4',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab4'
      )
    })
    observeEvent(input$next_tab_6, {
      js$enableTab('tab7')
      js$disableTab('tab6')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab7'
      )
    })
    observeEvent(input$previous_tab_6, {
      delay(50, {
        js$enableTab('tab5')
        js$disableTab('tab6')
      })
      removeTab('mainTabSet','tab6',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Register Visit",
          value = "tab6",
          registerVisitUpdateDB_ui(ns("mod6")),
          fluidRow(
            actionButton(ns('previous_tab_6'), label = "Previous"),
            actionButton(ns('next_tab_6'), label = "Next")
          )
        ),
        target = 'tab5',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab5'
      )
    })
    observeEvent(input$previous_tab_7, {
      delay(50, {
        js$enableTab('tab6')
        js$disableTab('tab7')
      })
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab6'
      )
    })
  })
}
