# This script was automatically generated by the shinymgr (vers. 1.0.0) R package's App Builder on 2023-07-03 15:56:27.490562.
# For more information, visit: https://code.usgs.gov/vtcfwru/shinymgr


jscode <- "
shinyjs.disableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.bind('click.tab', function(e) {
e.preventDefault();
return false;
});
tab.addClass('disabled');
}

shinyjs.enableTab = function(name) {
var tab = $('.nav li a[data-value=' + name + ']');
tab.unbind('click.tab');
tab.removeClass('disabled');
}
"

css <- "
.nav li a.disabled {
background-color: #bbb !important;
border-color: #ccc !important;
cursor: not-allowed !important;
}"


shiftMediaTime_ui <- function(id) {
  ns <- NS(id)
  tagList(
    fluidPage(
      useShinyjs(),
      extendShinyjs(text = jscode, functions = c('disableTab','enableTab')),
      inlineCSS(css),
      actionButton(
        ns("start"),
        "Start New Analysis",
        onclick = "var $btn=$(this); setTimeout(function(){$btn.remove();},0);"
      ),
      uiOutput(ns('appUI'))
    )
  )
}
shiftMediaTime_server <- function(id, userID, shinyMgrPath) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns
    observeEvent(input$start, {

      disable('start')

      output$appUI <- renderUI({
        tagList(
          tabsetPanel(
            id = ns("mainTabSet"),
            tabPanel(
              "Select Media", 
              value = "tab1",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                "Use the filters (steps 1-3) to select all media files associated with a visit. You can select a subset of media files associated with that visit in setp 4. All selected media files will be subject to modification of their startDate and startTime."
              ),
              selectMedia_ui(ns("mod1")),
              fluidRow(
                actionButton(ns('next_tab_1'), label = "Next")
              )
            ),
            tabPanel(
              "Shift Media Time", 
              value = "tab2",
              tags$br(),
              wellPanel(
                style = "background: skyblue",
                "Specify the number of minutes by which to shift (offset) the current startDate/startTime. Positive values will shift the time forward and negative values will shift the time backwards. The old and new (updated) times are shown in the table below, but you will need to click the \"Update Date/Time\" button to apply the changes to your database. A general note will be added to the associated visit indicating that a time shift has occurred."
              ),
              shiftMediaDateTime_ui(ns("mod2")),
              fluidRow(
                actionButton(ns('previous_tab_2'), label = "Previous"),
                actionButton(ns('next_tab_2'), label = "Next")
              )
            ),
            tabPanel(
              "Save",
              value = "tab3",
              save_analysis_ui(ns("mod3")),
              tags$br(),
              tags$br(),
              fluidRow(
                actionButton(ns("previous_tab_3"), label = "Previous")
              )
            )
          ),
          tags$p(tags$i("App created with shinymgr"), style = "text-align:right")
        )
      })
      delay(50, {
        js$disableTab("tab2")
        js$disableTab("tab3")
      })
    })

    data1 <- selectMedia_server("mod1")
    data2 <- shiftMediaDateTime_server("mod2", mediaType = data1$mediaType, mediaIDs = data1$mediaIDs)
    save_analysis_server("mod3",
      appName = "shiftMediaTime",
      moduleInput = input,
      returns = list(
        data1 = list(
          mediaType = data1$mediaType(),
          mediaIDs = data1$mediaIDs()
        ),
        data2 = list(
          shiftMinutes = data2$shiftMinutes(),
          status = data2$status()
        )
      ),
      metadata = list(
        appDescription = "",
        mod1 = list(
          dataset = "data1",
          modName = "selectMedia",
          modDisplayName = "Select a visit from the visits table.",
          modDescription = "Select the pkVisitID for row from the visits table.",
          modArguments = "This module has no additional arguments",
          modReturns = data.frame(
            name = c("mediaType","mediaIDs"),
            class = c("character","character"),
            description = c("Media type (photos/recordings)","Primary key values for selected media")
          ),
          modPackages = "This module has no package dependencies"
        ),
        mod2 = list(
          dataset = "data2",
          modName = "shiftMediaDateTime",
          modDisplayName = "Shift Media Date/Time.",
          modDescription = "Shift date/time of selected media by a specified amount.",
          modArguments = data.frame(
            name = c("mediaType","mediaIDs"),
            class = c("character","character"),
            description = c("Media type (photos/recoredings)","IDs of selected media items")
          ),
          modReturns = data.frame(
            name = c("status"),
            class = c("logical"),
            description = c("Status")
          ),
          modPackages = "This module has no package dependencies"
        ),
        lockfile = list(R = list(Version = "4.3.0", Repositories = list(CRAN = "https://cran.rstudio.com/")), Packages = list(shinydashboard = list(Package = "shinydashboard", Version = "0.7.2", Source = "Repository", Depends = "R (>= 3.0)", Imports = c("utils", "shiny (>= 1.0.0)", "htmltools (>= 0.2.6)", "promises"), Repository = "CRAN", Hash = "e418b532e9bb4eb22a714b9a9f1acee7"), bit = list(Package = "bit", Version = "4.0.4", Source = "Repository", Depends = "R (>= 2.9.2)", Repository = "CRAN", Hash = "f36715f14d94678eea9933af927bc15d"), jsonlite = list(Package = "jsonlite", Version = "1.8.4", Source = "Repository", 
    Depends = "methods", Repository = "CRAN", Hash = "a4269a09a9b865579b2635c77e572374"), renv = list(Package = "renv", Version = "0.15.5", Source = "Repository", Imports = "utils", Repository = "CRAN", Hash = "6a38294e7d12f5d8e656b08c5bd8ae34"), crayon = list(Package = "crayon", Version = "1.5.2", Source = "Repository", Imports = c("grDevices", "methods", "utils"), Repository = "CRAN", Hash = "e8a1e41acf02548751f45c718d55aa6a"), promises = list(Package = "promises", Version = "1.2.0.1", Source = "Repository", 
    Imports = c("R6", "Rcpp", "later", "rlang", "stats", "magrittr"), LinkingTo = c("later", "Rcpp"), Repository = "CRAN", Hash = "4ab2c43adb4d4699cf3690acd378d75d"), Rcpp = list(Package = "Rcpp", Version = "1.0.9", Source = "Repository", Imports = c("methods", "utils"), Repository = "CRAN", Hash = "e9c08b94391e9f3f97355841229124f2"), blob = list(Package = "blob", Version = "1.2.3", Source = "Repository", Imports = c("methods", "rlang", "vctrs (>= 0.2.1)"), Repository = "CRAN", Hash = "10d231579bc9c06ab1c320618808d4ff"), 
    sourcetools = list(Package = "sourcetools", Version = "0.1.7", Source = "Repository", Depends = "R (>= 3.0.2)", Repository = "CRAN", Hash = "947e4e02a79effa5d512473e10f41797"), jquerylib = list(Package = "jquerylib", Version = "0.1.4", Source = "Repository", Imports = "htmltools", Repository = "CRAN", Hash = "5aab57a3bd297eee1c1d862735972182"), later = list(Package = "later", Version = "1.3.0", Source = "Repository", Imports = c("Rcpp (>= 0.12.9)", "rlang"), LinkingTo = "Rcpp", Repository = "CRAN", 
        Hash = "7e7b457d7766bc47f2a5f21cc2984f8e"), yaml = list(Package = "yaml", Version = "2.3.5", Source = "Repository", Repository = "CRAN", Hash = "458bb38374d73bf83b1bb85e353da200"), fastmap = list(Package = "fastmap", Version = "1.1.0", Source = "Repository", Repository = "CRAN", Hash = "77bd60a6157420d4ffa93b27cf6a58b8"), mime = list(Package = "mime", Version = "0.12", Source = "Repository", Imports = "tools", Repository = "CRAN", Hash = "18e9c28c1d3ca1560ce30658b22ce104"), R6 = list(Package = "R6", 
        Version = "2.5.1", Source = "Repository", Depends = "R (>= 3.0)", Repository = "CRAN", Hash = "470851b6d5d0ac559e9d01bb352b4021"), shinymgr = list(Package = "shinymgr", Version = "1.0.0", Source = "unknown", Depends = c("R (>= 3.5.0)", "DBI", "reactable", "renv", "RSQLite", "shiny", "shinyjs", "shinydashboard"), Hash = "83de17c2f960356211dfc80b4f6d633c"), shinyjs = list(Package = "shinyjs", Version = "2.1.0", Source = "Repository", Depends = "R (>= 3.1.0)", Imports = c("digest (>= 0.6.8)", 
    "jsonlite", "shiny (>= 1.0.0)"), Repository = "CRAN", Hash = "802e4786b353a4bb27116957558548d5"), commonmark = list(Package = "commonmark", Version = "1.8.0", Source = "Repository", Repository = "CRAN", Hash = "2ba81b120c1655ab696c935ef33ea716"), htmlwidgets = list(Package = "htmlwidgets", Version = "1.5.4", Source = "Repository", Imports = c("grDevices", "htmltools (>= 0.3)", "jsonlite (>= 0.9.16)", "yaml"), Repository = "CRAN", Hash = "76147821cd3fcd8c4b04e1ef0498e7fb"), reactable = list(Package = "reactable", 
        Version = "0.3.0", Source = "Repository", Depends = "R (>= 3.1)", Imports = c("digest", "htmltools", "htmlwidgets", "jsonlite", "reactR"), Repository = "CRAN", Hash = "377c52754f3e6c17673c79740e9296d7"), shiny = list(Package = "shiny", Version = "1.7.3", Source = "Repository", Depends = c("R (>= 3.0.2)", "methods"), Imports = c("utils", "grDevices", "httpuv (>= 1.5.2)", "mime (>= 0.3)", "jsonlite (>= 0.9.16)", "xtable", "fontawesome (>= 0.4.0)", "htmltools (>= 0.5.2)", "R6 (>= 2.0)", "sourcetools", 
    "later (>= 1.0.0)", "promises (>= 1.1.0)", "tools", "crayon", "rlang (>= 0.4.10)", "fastmap (>= 1.1.0)", "withr", "commonmark (>= 1.7)", "glue (>= 1.3.2)", "bslib (>= 0.3.0)", "cachem", "ellipsis", "lifecycle (>= 0.2.0)"), Repository = "CRAN", Hash = "fe12df67fdb3b1142325cc54f100cc06"), DBI = list(Package = "DBI", Version = "1.1.3", Source = "Repository", Depends = c("methods", "R (>= 3.0.0)"), Repository = "CRAN", Hash = "b2866e62bab9378c3cc9476a1954226b"), bslib = list(Package = "bslib", Version = "0.4.0", 
        Source = "Repository", Depends = "R (>= 2.10)", Imports = c("grDevices", "htmltools (>= 0.5.2)", "jsonlite", "sass (>= 0.4.0)", "jquerylib (>= 0.1.3)", "rlang", "cachem", "memoise"), Repository = "CRAN", Hash = "be5ee090716ce1671be6cd5d7c34d091"), rlang = list(Package = "rlang", Version = "1.0.6", Source = "Repository", Depends = "R (>= 3.4.0)", Imports = "utils", Repository = "CRAN", Hash = "4ed1f8336c8d52c3e750adcdc57228a7"), cachem = list(Package = "cachem", Version = "1.0.6", Source = "Repository", 
        Imports = c("rlang", "fastmap"), Repository = "CRAN", Hash = "648c5b3d71e6a37e3043617489a0a0e9"), reactR = list(Package = "reactR", Version = "0.4.4", Source = "Repository", Imports = "htmltools", Repository = "CRAN", Hash = "75389c8091eb14ee21c6bc87a88b3809"), httpuv = list(Package = "httpuv", Version = "1.6.11", Source = "Repository", Depends = "R (>= 2.15.1)", Imports = c("Rcpp (>= 1.0.7)", "utils", "R6", "promises", "later (>= 0.8.0)"), LinkingTo = c("Rcpp", "later"), Repository = "CRAN", 
        Hash = "838602f54e32c1a0f8cc80708cefcefa"), fs = list(Package = "fs", Version = "1.5.2", Source = "Repository", Depends = "R (>= 3.1)", Imports = "methods", Repository = "CRAN", Hash = "7c89603d81793f0d5486d91ab1fc6f1d"), sass = list(Package = "sass", Version = "0.4.2", Source = "Repository", Imports = c("fs", "rlang (>= 0.4.10)", "htmltools (>= 0.5.1)", "R6", "rappdirs"), Repository = "CRAN", Hash = "1b191143d7d3444d504277843f3a95fe"), bit64 = list(Package = "bit64", Version = "4.0.5", Source = "Repository", 
        Depends = c("R (>= 3.0.1)", "bit (>= 4.0.0)", "utils", "methods", "stats"), Repository = "CRAN", Hash = "9fe98599ca456d6552421db0d6772d8f"), RSQLite = list(Package = "RSQLite", Version = "2.2.14", Source = "Repository", Depends = "R (>= 3.1.0)", Imports = c("bit64", "blob (>= 1.2.0)", "DBI (>= 1.1.0)", "memoise", "methods", "pkgconfig", "Rcpp (>= 1.0.7)"), LinkingTo = c("plogr (>= 0.2.0)", "Rcpp"), Repository = "CRAN", Hash = "086113da6af75461b8dc8d916dcf9620"), memoise = list(Package = "memoise", 
        Version = "2.0.1", Source = "Repository", Imports = c("rlang (>= 0.4.10)", "cachem"), Repository = "CRAN", Hash = "e2817ccf4a065c5d9d7f2cfbe7c1d78c"), cli = list(Package = "cli", Version = "3.6.0", Source = "Repository", Depends = "R (>= 3.4)", Imports = "utils", Repository = "CRAN", Hash = "3177a5a16c243adc199ba33117bd9657"), withr = list(Package = "withr", Version = "2.5.0", Source = "Repository", Depends = "R (>= 3.2.0)", Imports = c("graphics", "grDevices", "stats"), Repository = "CRAN", 
        Hash = "c0e49a9760983e81e55cdd9be92e7182"), magrittr = list(Package = "magrittr", Version = "2.0.3", Source = "Repository", Depends = "R (>= 3.4.0)", Repository = "CRAN", Hash = "7ce2733a9826b3aeb1775d56fd305472"), digest = list(Package = "digest", Version = "0.6.29", Source = "Repository", Depends = "R (>= 3.3.0)", Imports = "utils", Repository = "CRAN", Hash = "cf6b206a045a684728c3267ef7596190"), fontawesome = list(Package = "fontawesome", Version = "0.4.0", Source = "Repository", Depends = "R (>= 3.3.0)", 
        Imports = c("rlang (>= 0.4.10)", "htmltools (>= 0.5.1.1)"), Repository = "CRAN", Hash = "c5a628c2570aa86a96cc6ef739d8bfda"), xtable = list(Package = "xtable", Version = "1.8-4", Source = "Repository", Depends = "R (>= 2.10.0)", Imports = c("stats", "utils"), Repository = "CRAN", Hash = "b8acdf8af494d9ec19ccb2481a9b11c2"), base64enc = list(Package = "base64enc", Version = "0.1-3", Source = "Repository", Depends = "R (>= 2.9.0)", Repository = "CRAN", Hash = "543776ae6848fde2f48ff3816d0628bc"), 
    rappdirs = list(Package = "rappdirs", Version = "0.3.3", Source = "Repository", Depends = "R (>= 3.2)", Repository = "CRAN", Hash = "5e3c5dc0b071b21fa128676560dbe94d"), lifecycle = list(Package = "lifecycle", Version = "1.0.3", Source = "Repository", Depends = "R (>= 3.4)", Imports = c("cli (>= 3.4.0)", "glue", "rlang (>= 1.0.6)"), Repository = "CRAN", Hash = "001cecbeac1cff9301bdc3775ee46a86"), vctrs = list(Package = "vctrs", Version = "0.5.2", Source = "Repository", Depends = "R (>= 3.3)", 
        Imports = c("cli (>= 3.4.0)", "glue", "lifecycle (>= 1.0.3)", "rlang (>= 1.0.6)"), Repository = "CRAN", Hash = "e4ffa94ceed5f124d429a5a5f0f5b378"), glue = list(Package = "glue", Version = "1.6.2", Source = "Repository", Depends = "R (>= 3.4)", Imports = "methods", Repository = "CRAN", Hash = "4f2596dfb05dac67b9dc558e5c6fba2e"), plogr = list(Package = "plogr", Version = "0.2.0", Source = "Repository", Repository = "CRAN", Hash = "09eb987710984fc2905c7129c7d85e65"), ellipsis = list(Package = "ellipsis", 
        Version = "0.3.2", Source = "Repository", Depends = "R (>= 3.2)", Imports = "rlang (>= 0.3.0)", Repository = "CRAN", Hash = "bb0eec2fe32e88d9e2836c2f73ea2077"), pkgconfig = list(Package = "pkgconfig", Version = "2.0.3", Source = "Repository", Imports = "utils", Repository = "CRAN", Hash = "01f28d4278f15c76cddbea05899c5d6f"), htmltools = list(Package = "htmltools", Version = "0.5.2", Source = "Repository", Depends = "R (>= 2.14.1)", Imports = c("utils", "digest", "grDevices", "base64enc", 
    "rlang (>= 0.4.10)", "fastmap"), Repository = "CRAN", Hash = "526c484233f42522278ab06fb185cb26")))
      )
    )
    observeEvent(input$next_tab_1, {
      js$enableTab('tab2')
      js$disableTab('tab1')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab2'
      )
    })
    observeEvent(input$next_tab_2, {
      js$enableTab('tab3')
      js$disableTab('tab2')
      updateTabsetPanel(
        session, 'mainTabSet',
        selected = 'tab3'
      )
    })
    observeEvent(input$previous_tab_2, {
      delay(50, {
        js$enableTab('tab1')
        js$disableTab('tab2')
      })
      removeTab('mainTabSet','tab2',session)
      insertTab(
        inputId = 'mainTabSet',
        tab = tabPanel(
          title = "Shift Media Time",
          value = "tab2",
          shiftMediaDateTime_ui(ns("mod2")),
          fluidRow(
            actionButton(ns('previous_tab_2'), label = "Previous"),
            actionButton(ns('next_tab_2'), label = "Next")
          )
        ),
        target = 'tab1',
        position = 'after'
      )
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab1'
      )
    })
    observeEvent(input$previous_tab_3, {
      delay(50, {
        js$enableTab('tab2')
        js$disableTab('tab3')
      })
      updateTabsetPanel(
        session, 'mainTabSet',
                selected = 'tab2'
      )
    })
  })
}
