#' @name birdsDetect
#' @title Detect bird species using \code{\link[birdnetR:birdnet_model_tflite]{birdnetR}}
#' (BirdNET)
#' @description \code{birdsDetect} runs BirdNET (via the \code{birdnetR}
#' package) against recordings and either returns the detections for review
#' or inserts them into the modeloutputs table. Mirrors the calling
#' convention of \code{\link{scoresDetect}} (con/recordingNames/dbInsert/
#' showProgress).
#' @param con A connection to a SQLite or Postgres AMMonitor database.
#' @param recordingNames Default = 'all'. An optional character vector
#' specifying by name which recordings should be processed.
#' @param minConfidence Default = 0.1. Minimum BirdNET confidence to keep a
#' detection (passed through to
#' \code{birdnetR::predict_species_from_audio_file}).
#' @param speciesList Default = NULL. Character vector of common names to
#' restrict detections to, for this call only. Pass NA to disable species
#' filtering entirely (BirdNET's full global species list -- not
#' recommended, produces geographically implausible detections). If NULL,
#' speciesListPath is used instead.
#' @param speciesListPath Default = NULL. Filepath to a species list CSV
#' (one common name per line) managed with \code{\link{birdSpeciesList}} /
#' \code{\link{birdSpeciesAdd}} / \code{\link{birdSpeciesRemove}}. Ignored
#' if speciesList is supplied. One of speciesList or speciesListPath must
#' be provided.
#' @param modelVersion Default = 'v2.4'. BirdNET model version.
#' @param language Default = 'en_us'. Language for species common names.
#' @param dbInsert Default = FALSE. Logical flag for whether to insert
#' records generated by this function into the database. If TRUE, results
#' are inserted into modeloutputs, skipping anything already there for the
#' same model/recording/species/time (so it's safe to re-run). If FALSE,
#' results are returned as a data.frame for review, and nothing is written.
#' @param showProgress Default = FALSE. If TRUE, progress is printed while
#' recordings are processed.
#' @param numCores Default = 1. Number of CPU cores to use. When > 1,
#' recordings are split into that many chunks and processed concurrently via
#' \code{parallel::mclapply} (fork-based -- Unix/macOS only; falls back to
#' sequential with a warning on Windows). Each worker loads its own BirdNET
#' model instance rather than sharing the parent's, since a loaded TensorFlow
#' Lite interpreter isn't guaranteed to survive a fork cleanly.
#' @return A data.frame of detections (if dbInsert = FALSE), or invisible
#' NULL (if dbInsert = TRUE).
#' @details Species not yet present in the taxa table are dropped with a
#' warning naming them -- use \code{\link{taxaAdd}} to register new species
#' before they can be stored in modeloutputs. Recordings hosted remotely
#' (filepath starting with http/https, e.g. S3) are downloaded to a temp
#' file for analysis and removed immediately after.
#' @importFrom parallel mclapply splitIndices
#' @examples
#' \dontrun{
#'
#' # review first, without writing anything
#' birdscores <- birdsDetect(
#'   con = conx,
#'   recordingNames = "some_file.wav",
#'   speciesListPath = "birdnet_species_list.csv",
#'   dbInsert = FALSE
#' )
#'
#' # once you're happy with it
#' birdsDetect(
#'   con = conx,
#'   recordingNames = "all",
#'   speciesListPath = "birdnet_species_list.csv",
#'   dbInsert = TRUE,
#'   showProgress = TRUE
#' )
#' }
#' @export

birdsDetect <- function(
    con,
    recordingNames = "all",
    minConfidence = 0.1,
    speciesList = NULL,
    speciesListPath = NULL,
    modelVersion = "v2.4",
    language = "en_us",
    dbInsert = FALSE,
    showProgress = FALSE,
    numCores = 1
) {

  if (!requireNamespace("birdnetR", quietly = TRUE)) {
    stop("Package 'birdnetR' is required. Install with install.packages('birdnetR').")
  }

  # ---- Resolve the registered BirdNET model row ----
  model_name <- paste0("BirdNET_", modelVersion)
  modelID <- DBI::dbGetQuery(
    con,
    paste0("SELECT pk_modelid FROM models WHERE model_name = '", model_name, "';")
  )[, 1]
  if (length(modelID) == 0) {
    stop(
      "No model named '", model_name, "' found in the models table. ",
      "See inst/birdnet/Register_BirdNET_Model.R (or register it under a different modelVersion)."
    )
  }

  # ---- Resolve which recordings to process ----
  if (identical(recordingNames, "all")) {
    media <- DBI::dbGetQuery(con, "SELECT pk_mediaid, filename, filepath FROM media WHERE media_type = 'audio';")
  } else {
    in_list <- paste(sprintf("'%s'", recordingNames), collapse = ", ")
    media <- DBI::dbGetQuery(con, paste0("SELECT pk_mediaid, filename, filepath FROM media WHERE filename IN (", in_list, ");"))
  }

  if (nrow(media) == 0) {
    message("No matching recordings found.")
    return(invisible(NULL))
  }

  # ---- Load the model once, reused across all recordings ----
  model <- birdnetR::birdnet_model_tflite(version = modelVersion, language = language)

  # ---- Resolve species filter ----
  # BirdNET's filter_species must be in its internal "Scientific name_Common
  # name" label format, not plain common names -- convert here.
  if (identical(speciesList, NA)) {
    filter_species <- NULL  # no filtering -- full global BirdNET species list
  } else {
    common_names <- if (!is.null(speciesList)) {
      speciesList
    } else if (!is.null(speciesListPath)) {
      birdSpeciesList(speciesListPath)
    } else {
      stop("Provide either speciesList or speciesListPath (or speciesList = NA to disable filtering).")
    }

    all_labels <- birdnetR::read_labels(birdnetR::labels_path(model, language = language))
    label_common_names <- sub("^.*_", "", all_labels)

    filter_species <- all_labels[label_common_names %in% common_names]
    unmatched <- setdiff(common_names, label_common_names)
    if (length(unmatched) > 0) {
      warning(
        length(unmatched), " species in the species list don't match any BirdNET label and will be ignored: ",
        paste(unmatched, collapse = ", "),
        call. = FALSE
      )
    }
  }

  td <- tempdir(check = TRUE)

  # ---- Per-recording worker, shared by the sequential and parallel paths ----
  process_one_recording <- function(pk_mediaid, filename, filepath, use_model) {
    fp <- filepath
    is_remote <- grepl("^https?://", fp)
    local_path <- if (is_remote) {
      dest <- file.path(td, filename)
      ok <- tryCatch({
        utils::download.file(utils::URLencode(fp, reserved = FALSE), dest, mode = "wb", quiet = TRUE)
        TRUE
      }, error = function(e) FALSE, warning = function(w) FALSE)
      if (ok) dest else NA_character_
    } else if (file.exists(fp)) {
      fp
    } else {
      NA_character_
    }

    if (is.na(local_path)) {
      warning("Could not access recording for ", filename, "; skipping.", call. = FALSE)
      return(list(result = NULL, duration = NA_real_))
    }

    dur_sec <- tryCatch({
      wav_header <- tuneR::readWave(local_path, header = TRUE)
      wav_header$samples / wav_header$sample.rate
    }, error = function(e) NA_real_)

    preds <- tryCatch(
      birdnetR::predict_species_from_audio_file(
        use_model,
        local_path,
        min_confidence = minConfidence,
        filter_species = filter_species,
        keep_empty = TRUE
      ),
      error = function(e) {
        warning("BirdNET failed on ", filename, ": ", conditionMessage(e), call. = FALSE)
        NULL
      }
    )

    if (is_remote && file.exists(local_path)) unlink(local_path)
    if (is.null(preds)) return(list(result = NULL, duration = dur_sec))

    real_detections <- preds[!is.na(preds$common_name), ]

    result <- if (nrow(real_detections) == 0) {
      data.frame(
        fk_mediaid = pk_mediaid,
        fk_modelid = modelID,
        fk_taxonid = "no-species",
        x_min = NA_real_,
        x_max = NA_real_,
        y_min = NA_real_,
        y_max = NA_real_,
        value_num = NA_real_,
        stringsAsFactors = FALSE
      )
    } else {
      data.frame(
        fk_mediaid = pk_mediaid,
        fk_modelid = modelID,
        fk_taxonid = real_detections$common_name,
        x_min = real_detections$start,
        x_max = real_detections$end,
        y_min = NA_real_,
        y_max = NA_real_,
        value_num = real_detections$confidence,
        stringsAsFactors = FALSE
      )
    }

    list(result = result, duration = dur_sec)
  }

  # ---- Process one chunk of recordings (a "worker") ----
  # Each parallel worker loads its own model rather than reusing the
  # parent's, since a loaded TensorFlow Lite interpreter (with its own
  # internal thread pool) isn't guaranteed to survive a fork cleanly.
  process_chunk <- function(chunk_media, load_own_model) {
    chunk_model <- if (load_own_model) {
      birdnetR::birdnet_model_tflite(version = modelVersion, language = language)
    } else {
      model
    }
    chunk_results <- vector("list", nrow(chunk_media))
    chunk_duration <- 0
    chunk_processed <- 0
    for (i in seq_len(nrow(chunk_media))) {
      if (showProgress) cat(chunk_media$filename[i], "\n")
      out <- process_one_recording(
        chunk_media$pk_mediaid[i], chunk_media$filename[i], chunk_media$filepath[i], chunk_model
      )
      if (!is.na(out$duration)) chunk_duration <- chunk_duration + out$duration
      if (!is.null(out$result)) {
        chunk_results[[i]] <- out$result
        chunk_processed <- chunk_processed + 1
      }
    }
    list(results = do.call(rbind, chunk_results), duration = chunk_duration, processed = chunk_processed)
  }

  numCores <- max(1L, as.integer(numCores))
  use_parallel <- numCores > 1 && nrow(media) > 1
  if (use_parallel && .Platform$OS.type != "unix") {
    warning("Multicore processing (fork-based) isn't available on Windows; running sequentially.", call. = FALSE)
    use_parallel <- FALSE
  }

  start_time <- Sys.time()

  if (use_parallel) {
    n_workers <- min(numCores, nrow(media))
    chunks <- lapply(parallel::splitIndices(nrow(media), n_workers), function(idx) media[idx, , drop = FALSE])
    worker_out <- parallel::mclapply(chunks, process_chunk, load_own_model = TRUE, mc.cores = n_workers)

    failed <- vapply(worker_out, inherits, logical(1), "try-error")
    if (any(failed)) {
      warning(sum(failed), " of ", length(worker_out), " parallel worker(s) failed and were skipped: ",
              paste(vapply(worker_out[failed], conditionMessage, character(1)), collapse = "; "),
              call. = FALSE)
      worker_out <- worker_out[!failed]
    }
  } else {
    worker_out <- list(process_chunk(media, load_own_model = FALSE))
  }

  elapsed_sec <- as.numeric(difftime(Sys.time(), start_time, units = "secs"))
  total_duration_sec <- sum(vapply(worker_out, `[[`, numeric(1), "duration"))
  n_processed <- sum(vapply(worker_out, `[[`, numeric(1), "processed"))
  if (showProgress && n_processed > 0) {
    reportDetectionSpeed(n_processed, elapsed_sec, total_duration_sec)
  }

  results <- do.call(rbind, lapply(worker_out, `[[`, "results"))

  if (is.null(results) || nrow(results) == 0) {
    message("No results produced.")
    return(invisible(NULL))
  }

  # Drop (with a warning) any species not yet registered as taxa -- a
  # foreign key violation would otherwise reject the whole insert.
  known_taxa <- DBI::dbGetQuery(con, "SELECT pk_taxonid FROM taxa;")[, 1]
  unknown <- setdiff(unique(results$fk_taxonid), known_taxa)
  if (length(unknown) > 0) {
    warning(
      length(unknown), " detected species are not yet registered in the taxa table and were dropped: ",
      paste(unknown, collapse = ", "),
      ". Use taxaAdd() to add them, then re-run birdsDetect().",
      call. = FALSE
    )
    results <- results[results$fk_taxonid %in% known_taxa, ]
  }

  if (nrow(results) == 0) {
    message("Nothing left to insert after dropping unregistered species.")
    return(invisible(NULL))
  }

  if (!dbInsert) {
    rownames(results) <- NULL
    return(results)
  }

  # Skip anything already in modeloutputs for this model+file+species+time,
  # so re-running birdsDetect() on the same recordings is a no-op for
  # anything already stored (mirrors scoresDetect's dedup-before-insert).
  existing <- DBI::dbGetQuery(
    con,
    paste0(
      "SELECT fk_mediaid, fk_taxonid, x_min, x_max FROM modeloutputs WHERE fk_modelid = ", modelID,
      " AND fk_mediaid IN (", paste(unique(results$fk_mediaid), collapse = ", "), ");"
    )
  )
  if (nrow(existing) > 0) {
    dup_key <- function(df) paste(df$fk_mediaid, df$fk_taxonid, df$x_min, df$x_max, sep = "|")
    results <- results[!(dup_key(results) %in% dup_key(existing)), ]
  }

  if (nrow(results) == 0) {
    message("All results already exist in modeloutputs; nothing new to insert.")
    return(invisible(NULL))
  }

  rownames(results) <- NULL
  DBI::dbAppendTable(con, "modeloutputs", results)
  message("Inserted ", nrow(results), " new modeloutputs rows.")
  invisible(NULL)
}
