#' @name classifierPredict
#' @aliases classifierPredict
#' @title Classify template detections into true and false positives
#' @description \code{classifierPredict} runs classifier models (which are 
#' trained 
#' to classify the detections from a particular template) on all detections of 
#' a 
#' template in order to determine whether the detections are true or false 
#' positives. Please see the "models" tutorial for information on this function.
#' \code{learnr::run_tutorial("models", package = "AMMonitor")}
#' @param con An open database connection
#' @param classifierName A character vector specifying which classifier model to 
#' run.
#' @param recordingNames Default = 'all'. An optional character vector specifying 
#' by name which recordings should be processed. 
#' @param recordingRootPath A character string indicating the path to the 
#' directory 
#' containing the recordings, can be local or a URL. If NULL, will use the path 
#' indicated by the media.filepath column in the database.
#' @param ammlPath A character string indicating the path to the directory where
#'  AMModel Libraries are stored.
#' @param dbInsert Default = FALSE. Logical flag for whether to insert records 
#' generated by this function into the database. If TRUE, events are added to the 
#' database. If FALSE, events are returned as a data.table for examination by 
#' the user, but not added to the database.
#' @param showProgress Default = FALSE. If TRUE, progress will be reported during 
#' the retrieval of data. 
#' @return Data.table of scores
#' @usage classifierPredict(con,
#'  classifierName,
#'  recordingNames = 'all',
#'  recordingRootPath = 'recordings/',
#'  ammlPath = 'ammls/',
#'  dbInsert = FALSE,
#'  showProgress = FALSE)
#' @importFrom DBI dbGetQuery dbSendQuery dbFetch dbBind dbClearResult
#' @importFrom AMModels getAMModel
#' @importFrom methods is
#' @importFrom utils txtProgressBar setTxtProgressBar download.file
#' @importFrom seewave spectro
#' @importFrom data.table rbindlist
#' @importFrom tuneR readWave
#' @import caret 
#' @export
#' 

classifierPredict <- function(
    con,
    classifierName,
    recordingNames = 'all',
    recordingRootPath = 'recordings/',
    ammlPath = 'ammls/', 
    dbInsert = FALSE,
    showProgress = FALSE) {
  
  # Get classifier record
  classifier_info <- getClassifierInfo(con, classifierName)
  
  templateID <- classifier_info$fk_parentid
  
  # Read in classifier from AMML
  classifier <- loadModels(classifier_info, ammlPath)[[classifier_info$model_name]]
  
  if (is.null(classifier)) {
    stop("The classifier was not found in the AMMonitor model libraries.")
  }
  
  # Get template detections
  recordingIDs <- getAudioIDs(con, recordingNames)
  td <- getTemplateDetections(con, templateID, recordingRootPath, recordingIDs$pk_mediaid, showProgress)
  
  # Get combinations of classifiers and detections that haven't been run before
  if (dbInsert == TRUE) {
    # Query database for existing model outputs
    outputs_str <- paste(td$pk_modeloutputid, collapse = ", ")
    combos <- DBI::dbGetQuery(
      con,
      paste0(
        "SELECT fk_parentid 
      FROM modeloutputs 
      WHERE fk_parentid IN (", outputs_str, ") 
      AND fk_modelid = ", classifier_info$pk_modelid,
      ";"
      )
    )$fk_parentid
    
    # Make list of which IDs shouldn't be rerun
    index <- c()
    for (i in seq_len(nrow(td))) {
      # Check if each detection has already been classified by this model
      if (!(td$pk_modeloutputid[i] %in% combos)) {
        index <- c(index, i)
      }
    }
    td <- td[index,]
  }
  
  # Predict
  td_data <- td[-which(names(td) %in% c("pk_modeloutputid", "fk_mediaid", "x_min", "x_max", "y_min", "y_max", "timestamp"))]
  preds <- caret::predict.train(classifier, newdata=td_data, type = "raw")
  # probs <- caret::predict.train(classifier, newdata=td_data, type = "prob")
  
  # Format predictions
  scores <- td[c('fk_mediaid', 'x_min', 'x_max', 'y_min', 'y_max')]
  scores$fk_modelid <- classifier_info$pk_modelid
  scores$fk_parentid <- td$pk_modeloutputid
  scores$fk_taxonid <- ifelse(preds == "TP", classifier_info$fk_taxonid, "no-species")
  
  if (dbInsert == TRUE) {
    dbAppendTable(
      con,
      'modeloutputs',
      scores
    )
  }
  
  return(scores)
}

#' @name getClassifierInfo
#' @title Get information about a classifier
#' @description An internal function that retrieves information about a classifier from an AMMonitor database.
#' @param con A connection to a SQLite or Postgres AMMonitor database.
#' @param classifierName A character vector specifying which classifier to run on template detections.

getClassifierInfo <- function(con, classifierName) {
  
  # Get classifier info
  if (is.character(classifierName)) {
    rs <- DBI::dbSendQuery(
      con, 
      "SELECT pk_modelid, model_name, model_type, amml, fk_taxonid, fk_parentid 
      FROM models WHERE model_name = $1"
    )
    DBI::dbBind(rs, list(classifierName))
    class_info <- DBI::dbFetch(rs)
    DBI::dbClearResult(rs)
  } else {
    stop("ClassifierName must be a character vector - the name of the classifier model")
  }
  
  if (nrow(class_info) == 0) {
    stop("The model was not found in the database. Please verify that it has not been deleted and check for spelling errors.")
  }
  
  return(class_info)
}

#' @name loadModels
#' @title Get models from one or more AMModels libraries
#' @description An internal function that retrieves models from AMModels libraries.
#' @param model_info A dataframe containing information about classifier, as stored in the AMMonitor database
#' @param ammlPath A character string indicating the path to the directory where AMModels Libraries are stored.

loadModels <- function(model_info, ammlPath = "/ammls") {
  # Remove trailing slash in root path
  if (grepl("\\/$", ammlPath)) {
    ammlPath <- substr(ammlPath, 1, nchar(ammlPath) - 1)
  }
  models <- list()
  for (amml in unique(model_info$amml)) {
    modelLib <- readRDS(file.path(ammlPath, amml))
    if (methods::is(modelLib, "amModelLib")) {
      for (temp_name in model_info[which(model_info$amml == amml), 'model_name']) {
        tryCatch(
          {
            models[[temp_name]] <- AMModels::getAMModel(modelLib, temp_name)
          },
          error = function(e) {
            message(paste0('Model ', temp_name, ' not found in model library ', amml, ', skipping.'))
          }
        )
      }
    } else {
      stop("The AMModels library was not found.")
    }
  }
  return(models)
}

#' @name getTemplateDetections
#' @title Retrieves detections of a particular template from an AMMonitor database
#' @description An internal function that retrieves a particular template's detections from an AMMonitor database.
#' @param con A connection to an AMMonitor database.
#' @param templateID The integer pk_templateID of a template in an AMMonitor database.
#' @param recordingRootPath A character string indicating the path to the directory containing the recordings, can be local or a URL.
#' @param recordingIDs An integer vector of recording IDs to filter detections by.
#' default is NULL, which gets all detections.
#' @param showProgress Default = FALSE. If TRUE, progress will be reported during the score calculations. 
#' @importFrom utils txtProgressBar setTxtProgressBar
#' @importFrom seewave spectro
#' @importFrom data.table rbindlist
#' @importFrom tuneR readWave

getTemplateDetections <- function(con, templateID, recordingRootPath, recordingIDs = NULL, showProgress = FALSE) {
  # Get dataframe of template IDs
  stmnt <- "SELECT pk_modeloutputid, fk_mediaid, x_min, x_max, y_min, y_max, value_num, timestamp
    FROM modeloutputs WHERE fk_modelid = $1"
  
  params <-  list(templateID)
  
  if (length(recordingIDs) >= 1 && is.numeric(recordingIDs)) {
    stmnt <- paste0(stmnt, " AND fk_mediaid IN ($2)")
    params <- append(params, paste(recordingIDs, collapse = ", "))
  } else {
    message("No audio files specified, proceeding with all detections.")
  }
  
  rs <- DBI::dbSendQuery(con, stmnt)
  DBI::dbBind(rs, params)
  detections <- DBI::dbFetch(rs)
  DBI::dbClearResult(rs)
  
  if (nrow(detections) == 0) {
    stop(paste0("No detections were found for template ", templateID, "."))
  }
  
  # Get spectrogram for each detection
  if (grepl("\\/$", recordingRootPath)) {
    recordingRootPath <- substr(recordingRootPath, 1, nchar(recordingRootPath) - 1)
  }
  
  media_ids <- unique(detections$fk_mediaid)
  media <- DBI::dbGetQuery(
    con, 
    paste0(
      "SELECT * FROM media WHERE pk_mediaid IN (",
      paste(media_ids, collapse = ", "),
      ")"
    )
  )
  
  if (showProgress == TRUE) {
    pb <- utils::txtProgressBar(max = nrow(detections), style = 3)
    row_counter <- 1
  }
  
  bboxes <- list()
  
  for (i in seq_len(nrow(media))) {
    media_subset <- media[i,]
    det_subset <- detections[which(detections$fk_mediaid == media_subset$pk_mediaid),]
    
    audio_path <- ifelse(
      is.null(recordingRootPath) || recordingRootPath == "",
      media_subset$filepath,
      file.path(recordingRootPath, media_subset$filename)
    )
    
    tryCatch(
      {
        if (grepl("^www.|^http:|^https:", audio_path)) {
          temp.file <- tempfile()
          utils::download.file(
            url = audio_path, 
            destfile = temp.file, 
            quiet = TRUE, 
            mode = "wb", 
            cacheOK = TRUE
          )
          if (!file.exists(temp.file)) stop("File couldn't be downloaded")
          audio_wave <- tuneR::readWave(temp.file)
        } else {
          audio_wave <- tuneR::readWave(audio_path)
        }
    
        for (modeloutput in det_subset$pk_modeloutputid) {
          mo_row <- det_subset[which(det_subset$pk_modeloutputid == modeloutput),]
          bboxes[[as.character(modeloutput)]] <- seewave::spectro(
            audio_wave,
            tlim = c(mo_row$x_min, mo_row$x_max),
            flim = c(mo_row$y_min, mo_row$y_max),
            plot = FALSE
          )
          if (showProgress == TRUE) {
            utils::setTxtProgressBar(pb, row_counter)
          }
        }
      },
      error = function(e) {
        message("Error in retrieving spectrogram for modeloutput ", modeloutput, ": ", e)
      },
      finally = {
        if (showProgress == TRUE) {
          row_counter <- row_counter + 1
        }
      }
    )
  }
  
  bboxes_long <- lapply(bboxes, function(x) {
    as.data.frame(t(as.vector(x$amp)))
  })
  
  bboxes_df <- as.data.frame(
    data.table::rbindlist(bboxes_long, use.names = TRUE, idcol = "pk_modeloutputid")
  )
  
  td <- merge(detections, bboxes_df, how = 'left', by = 'pk_modeloutputid')
  
  return(td)
}
