#' @name dbCheckup
#' @title Performs basic database integrity checks
#' @description Checks database integrity by identifying any foreign key
#' constraints, as well as checking if the dbdictionary table matches
#' the current database schema.
#' @param con An open database connection
#' @param errors_only TRUE or FALSE.  Should only database errors be returned?
#' @param disconnect TRUE or FALSE. Should the database connection be severed
#' on exit? Default is FALSE
#' @importFrom DBI dbIsValid dbDisconnect dbGetQuery dbReadTable dbListTables
#' @usage dbCheckup(con, errors_only = TRUE, disconnect = FALSE)
#' @details  dbCheckup() is an important function to run occasionally to ensure
#' that there are no foreign key violations present in the database, as well
#' as to ensure that the dbdictionary database table accurately reflects the
#' current database schema (tables and columns).  This is especially important
#' when releasing data to the public on ScienceBase, as the release will include
#' the dbdictionary table as a csv file and is used to re-create the original
#' release data with information on the ScienceBase release page.
#' 
#' The output is a list with four sections- one a list "description" with a 
#' short explanation of any errors found, and three data.frames containing
#' any errors encountered during the checks.  The 
#' goal is to yield empty data.frames in each section.  In "violations", a 
#' data.frame is returned that provides a list of foreign key violations.  
#' The offending table and row is provided in the columns "table" and "rowid".  
#' The parent table that enforces the keys is given, as well as the foreign key
#' identification "fkid". A violation means that an entry in 
#' the table that has a foreign key restriction contains data that violates the
#' key.
#' 
#' The second section named "tables" provides a check of the database structure.
#' It compares the actual database structure defined in its schema (column name,
#' variable type) with those identified in the database dictionary table.  
#' Columns with the prefix "db_" indicate information generated by the actual
#' database, while the prefix "dict_" indicates what is stored in the 
#' dictionary. The column "col_test" tests if the columns names match; the 
#' column "pk_test" tests if the database primary keys match the dictionary;
#' the column "type_test" tests if the database data type matches the
#' dictionary. The column "errors" flags whether any mismatches occur.
#' 
#' The final list element is "foreign_keys", and this data.frame returns a 
#' check between the foreign key constraints as specified in the database 
#' schema with those identified in the dbdictionary table.
#' The columns "missing_key_test", "child_test", and "parent_test", 
#' "on_update_test", "on_delete_test" should be TRUE if they pass. The 
#' "missing_key_test" checks that the key exists. The "child_test" checks that 
#' the database fieldname matches the dbdictionary fieldname for that key. The 
#' "parent_test" checks that the database is mapping to the correct foreign 
#' key field as defined in the dbdictionary. The "on_update_test" and 
#' "on_delete_test" make sure the on_update and on_delete fields match between 
#' the database schema and the dictionary. 
#' The column "errors" will identify if any of the tests fail for each table 
#' and field that contains a foreign key.
#' 
#' See the "database" learnr tutorial for more details on the
#' database. The tutorial can be launched with
#' \code{learnr::run_tutorial(name = "database", package = "AMMonitor")}.
#' 
#' @export
#' @family database
#' @examples
#' \dontrun{
#' 
#' # create a demo AMMonitor file structure in a temporary directory
#' # (to be deleted)
#' 
#' # run the function and capture the connection
#' demo_fp <- ammCreateMiniDemo(filepath = tempdir())
#' 
#' # look at the demo_fp
#' demo_fp
#' 
#' # to work with the database, set a connection
#' conx <- dbSetCon(paste0(demo_fp, "/database/demo.sqlite"))
#' 
#' # list the tables in the AMMonitor database
#' DBI::dbListTables(conx)
#' 
#' # check the database; do not disconnect on exit
#' results <- dbCheckup(con = conx, errors_only = TRUE, disconnect = FALSE)
#'  
#' # the errors, if present, will be given in the captured output
#' str(results)
#' 
#' # -----------------------------------------------------
#' # the demo has no errors
#' # let's change some data entries so you can see an error returned
#' 
#' # note that we cannot add foreign key errors into the database using the 
#' # DBI package due to foreign key constraints.
#' 
#' 
#' # produce column mismatch
#' DBI::dbExecute(
#'  conx, 
#'  statement = "UPDATE dbdictionary SET pk_fieldname = 'primary' 
#'    WHERE pk_fieldname = 'primary_account';"
#'  ) 
#'
#' # check the database again; disconnect from database
#' results <- dbCheckup(con = conx, errors_only = TRUE, disconnect = TRUE)
#'
#' # look at the structure of the results
#' str(results)

#' # -----------------------------------------------------
#' 
#' # remove the demo AMMonitor file structure
#' unlink(demo_fp, recursive = TRUE)
#' 
#' 
#' }

dbCheckup <- function(con, errors_only = TRUE, disconnect = FALSE) {
  
  # check if valid connection
  if (DBI::dbIsValid(con) == FALSE) stop("The database connection is not valid.")
  
  # disconnect on exit if requested
  if (disconnect == TRUE) {
    on.exit(expr = {
      DBI::dbDisconnect(con)
    })
  }
  
  # retrieve foreign key violations
  violations <- DBI::dbGetQuery(
    conn = con,
    statement = "PRAGMA foreign_key_check;"
  )
  
  # read in the database dictionary
  dictionary <- DBI::dbReadTable(con, name = "dbdictionary")
  
  # get the tables from the actual database
  tbls <- DBI::dbListTables(conn = con)
  
  # create  data frames for storing results
  table_results = data.frame()
  foreign_key_results = data.frame()
  
  # loop through tables and compare against dictionary
  for (i in 1:length(tbls)) {
    
    #-------check columns -----------------
    
    # read in the db table info
    tbl <- DBI::dbGetQuery(con, statement = paste0("PRAGMA table_info(", tbls[i], ")"))
    names(tbl) <- c("cid", "db_name", "db_type", "db_notnull", "db_dflt_value", "db_pk")
    
    # extract dictionary information
    tbl_dictionary <- dictionary[which(dictionary$pk_tablename == tbls[i]), ]
    col_dictionary <- tbl_dictionary[, c("pk_tablename", "pk_fieldname", "core", "var_type", "pk")]
    
    # merge db info with dictionary info
    tbl_merge <- merge(tbl, col_dictionary, by.x = "db_name", by.y = "pk_fieldname", all.y = T)
    
    # order columns
    cols <- c("cid", "pk_tablename", "db_name", "pk", "db_pk",  "var_type", "db_type")
    tbl_merge <- tbl_merge[order(tbl_merge$cid, decreasing = FALSE), cols]
    
    tbl_merge$col_test <- !is.na(tbl_merge$cid)
    tbl_merge$pk_test <- tbl_merge$db_pk >= tbl_merge$pk 
    tbl_merge$type_test <- tolower(tbl_merge$db_type) == tolower(tbl_merge$var_type)
    tbl_merge$errors <- 3 - (tbl_merge$col_test + tbl_merge$pk_test + tbl_merge$type_test)
    
    indices <-  is.na(tbl_merge$errors)
    if (sum(indices) > 0) {
      tbl_merge[indices, "errors"] <- 1
    }
    
    # rename results fields for user clarity
    names(tbl_merge) <- c('col_id', 'dict_tablename', 'db_fieldname', 'dict_pk', 'db_pk', 'dict_vartype', 'db_vartype', 'col_test', 'pk_test', 'type_test', 'errors' )
   
    # if tests are NA, make FALSE
    for (row in 1:nrow(tbl_merge)) {
      if (is.na(tbl_merge$col_test[row])) {
        tbl_merge$col_test[row] <- FALSE
      }
      
      if(is.na(tbl_merge$pk_test[row])) {
        tbl_merge$pk_test[row] <- FALSE
      }
      
      if(is.na(tbl_merge$type_test[row])) {
        tbl_merge$type_test[row] <- FALSE
      }
    }
   
     # bind the table results
    table_results <- rbind(table_results, tbl_merge) 
    
    #-------check foreign keys -----------------
    
    fks <- DBI::dbGetQuery(con, statement = paste0("PRAGMA foreign_key_list(", tbls[i], ")"))
    names(fks) <- c("id", "seq", "db_table", "db_from", "db_to", "db_on_update", "db_on_delete", "match")
    
    # get the dictionary keys
    fk_dictionary <- tbl_dictionary[, c("pk_tablename", "pk_fieldname", "foreign_key_table", 
                                        "foreign_key_field", "on_update", "on_delete")]
    
    # merge the database keys and dictionary keys
    key_merge <- merge(fks, fk_dictionary, by.x = "db_table", by.y = "foreign_key_table", all.x = TRUE)
    
    # order columns
    cols <- c("id", "pk_tablename", "db_table", "pk_fieldname", "db_from", "foreign_key_field",
              "db_to", "on_update", "on_delete", "db_on_update", "db_on_delete")
    key_merge <- key_merge[order(key_merge$id, decreasing = FALSE), cols]
    
    if (nrow(key_merge) == 0) next
    
    # set the tests of equality
    key_merge$missing_key_test <- !is.na(key_merge$id)
    key_merge$child_test <- key_merge$db_from == key_merge$pk_fieldname
    key_merge$parent_test <- key_merge$db_to == key_merge$foreign_key_field
    key_merge$on_update_test <- key_merge$db_on_update == key_merge$on_update
    key_merge$on_delete_test <- key_merge$db_on_delete == key_merge$on_delete
    
    key_merge$errors <- 5 - (key_merge$missing_key_test + key_merge$child_test +  key_merge$parent_test +
                               key_merge$on_update_test + key_merge$on_delete_test)
    
    indices <-  is.na(key_merge$errors)
    if (sum(indices) > 0) {
      key_merge[indices, "errors"] <- 1
    }
    
    
    names(key_merge) <- c('col_id', 'dict_tablename', 'db_tablename',  "dict_fieldname", "db_fieldname",  "dict_fk_field", "db_fk_field","dict_on_update", "dict_on_delete", "db_on_update", "db_on_delete", "missing_key_test", "child_test", "parent_test", "on_update_test", "on_delete_test", "errors")
    # bind the  results
    foreign_key_results <- rbind(foreign_key_results, key_merge)   

  } # end of tbl i

  
  row.names(table_results) <- NULL
  row.names(foreign_key_results) <- NULL
  
  # count errors
  sum_violations <- nrow(violations)
  sum_col_errors <- sum(table_results$errors)
  sum_key_errors <- sum(foreign_key_results$errors)
  
  # retain only errors if requested
  if (errors_only == TRUE) {
    table_results <- table_results[which(table_results$errors != 0),]
    foreign_key_results <- foreign_key_results[which(foreign_key_results$errors != 0),]
  }
  
  
  # Create description
  description_message <- c()
  
  
  if (sum_violations > 0 ) {
    for (i in 1:nrow(violations)) {
      description_message <- c(description_message,
                               paste0("A foreign key violation was found in row ",
                                      violations$rowid[i], " of the '",
                                      violations$table[i], "' table. ",
                                      "The parent table is '", 
                                      violations$parent[i],
                                      "' and the foreign key id is '",
                                      violations$fkid, "'."))
    }
  }
 
  if (sum_col_errors > 0) {
    for (i in 1:nrow(table_results)) {
      description_message <- c(description_message,
                               paste0("The column '",
                                      table_results$db_fieldname[i], 
                                      "' in the table '",
                                      table_results$dict_tablename[i],
                                      "' does not exist in the dbdictionary."))
    }
  }
  
  if (sum_key_errors > 0) {
    for (i in 1:nrow(foreign_key_results)) {
      description_message <- c(description_message,
                               paste0("There is a discrepancy between the database schema and the 'dbdictionary' within the table '", foreign_key_results$dict_tablename[i], 
                                      "'. See the list item 'foreign keys' to see where in the database the error occurred and which tests failed."))
    }
  }
  
  if (length(description_message) == 0) {
    description_message <- c(paste0('Congratulations! No foreign key ',
                                    'constraints or discrepancies between the ',
                                    'database and the dbdictionary were found.'))
  }
  
  # send messages
  
  message(paste0("Your database has ", sum_violations, " foreign key violations.
  See the list item 'violations' for more details."))
  
  message(paste0("There are ", sum_col_errors, " column mismatches between
  the actual database and dictionary.  See the list item 'tables' for more details."))
  
  message(paste0("There are ", sum_key_errors, " foreign key mismatches between
  the actual database and dictionary.  See the list item 'foreign_keys' for more details."))
  
  # return result as list
  return(list(violations = violations,
              tables = table_results,
              foreign_keys = foreign_key_results[,c("col_id", "dict_tablename", "db_tablename", "dict_fieldname", "db_fieldname", "dict_fk_field", "db_fk_field", "missing_key_test", "child_test", "parent_test", "on_update_test", "on_delete_test", "errors")],
              description = description_message))
  
}
