#' @name scoresDetect
#' @title Detect events using \code{\link[monitoR:makeTemplate]{monitoR}}
#' templates
#' @description \code{scoresDetect} calls monitoR's \code{templateMatching()}
#' function to run spectrogram cross correlation or binary point matching templates
#' in search of target signals within recordings. While running template matching,
#' \code{scoresDetect} also extracts acoustic features associated with each
#' detected event (see the Details section). To indicate which recordings should
#' be run in \code{scoresDetect}, supply the recordingNames. To indicate which
#' templates should be run against recordings, provide the name(s) of templates
#' as stored in the models table of the AMMonitor database, and further supply
#' the path to the AMModels library that stores the RDS template library.
#' @param con A connection to a SQLite or Postgres AMMonitor database.
#' @param recordingNames Default = 'all'. An optional character vector specifying
#' by name which recordings should be processed. Default is 'all'.
#' @param templateNames Default = 'all'. An optional character vector specifying
#' which templates to use for searching recordings.
#' @param scoreThresholds Optional named numeric vector of score thresholds to
#' use for binary point matching or spectrogram cross correlation templates,
#' ordered according to inputs to the templateID or listID argument. If using
#' \code{templateID = 'all'}, please check the current ordering of templates in
#' your database to ensure you are providing the correct score thresholds to the
#' templateNames you intend. If no value is entered for scoreThresholds, all
#' template score thresholds will be automatically extracted from the internals
#' of the monitoR templateList object -- please check to ensure these are the
#' score thresholds you actually want to use.
#' @param recordingRootPath A character string indicating the path to the directory
#' containing the recordings, can be local or a URL.
#' @param ammlPath A character string indicating the path to the directory where
#' AMModel Libraries are stored.
#' @param dbInsert Default = FALSE. Logical flag for whether to insert records
#' generated by this function into the database. If TRUE, events are added to the
#' database. If FALSE, events are returned as a data.table for examination by the
#' user, but not added to the database. Setting dbInsert = TRUE will also remove
#' duplicate records before inserting into the database.
#' @param showProgress Default = FALSE. If TRUE, progress will be reported during
#' the score calculations.
#' @param corMethod Default = 'pearson'. For spectrogram cross correlation templates,
#' the method used to calculate correlation coefficients (see \code{?cor}).
#' @return Data.table of scores
#' @importFrom DBI dbGetQuery dbSendQuery dbFetch dbBind dbClearResult
#' @importFrom AMModels getAMModel
#' @import monitoR
#' @importFrom tuneR readWave
#' @importFrom methods as new
#' @importFrom utils download.file
#' @details
#' The recording root path argument can be NA.
#'
#' @export
#' @examples
#' \dontrun{
#'
#' # create a demo AMMonitor file structure in a temporary directory
#' # (to be deleted)
#'
#' # run the function and capture the connection
#' demo_fp <- ammCreateMiniDemo(filepath = tempdir())
#'
#' # look at the demo_fp
#' demo_fp
#'
#' # look at the sample recordings in the recordings directory
#' list.files(paste0(demo_fp, "/recordings"), recursive = FALSE)
#'
#' # look at the sample ammodels library that stores templates in the amml directory
#' list.files(paste0(demo_fp, "/ammls"), recursive = FALSE)
#'
#' # read in the "templates" model library; note there are 4 templates
#' templates <- readRDS(paste0(demo_fp, "/ammls/templates.RDS"))
#' templates
#'
#' # to work with the database, set a connection
#' conx <- dbSetCon(file.path(demo_fp, "database", "demo.sqlite"))
#'
#' # Let's look at the modeloutputs table
#' DBI::dbReadTable(conx, name = 'modeloutputs')
#'
#' # clear out the pre-populated modeloutputs table
#' DBI::dbExecute(conx, statement = "DELETE FROM modeloutputs;")
#'
#' # run scoresDetect to match the 4 templates against 1.wav
#' scores <- scoresDetect(
#'   con = conx,
#'   recordingNames = "1.wav",
#'   recordingRootPath = paste0(demo_fp, "/recordings"),
#'   ammlPath = paste0(demo_fp, "/ammls"),
#'   dbInsert = FALSE
#'  )
#'
#'  # look at the scores
#'  scores
#'
#' # rerun the function is dbInsert is TRUE
#' scoresDetect(
#'   con = conx,
#'   recordingNames = "1.wav",
#'   recordingRootPath = paste0(demo_fp, "/recordings"),
#'   ammlPath = paste0(demo_fp, "/ammls"),
#'   dbInsert = TRUE
#'  )
#'  
#'  # rerun the function with scoreThresholds specified
#'  
#'  newThresholds <- c(.55, 16, .55, 14)
#'  names(newThresholds) <-  names(templates@models)
#'
#'
#'  scores_newThreshold <- scoresDetect(
#'   con = conx,
#'   recordingNames = "1.wav",
#'   scoreThresholds = newThresholds,
#'   recordingRootPath = paste0(demo_fp, "/recordings"),
#'   ammlPath = paste0(demo_fp, "/ammls"),
#'   dbInsert = FALSE
#'  )
#'
#' # check the modeloutputs table
#' DBI::dbReadTable(conx, name = 'modeloutputs')
#'
#' }

scoresDetect <- function(
    con,
    recordingNames = 'all',
    templateNames = 'all',
    scoreThresholds = NA,
    recordingRootPath = 'recordings/',
    ammlPath = 'amml/',
    dbInsert = FALSE,
    showProgress = FALSE,
    corMethod = 'pearson') {

  # Get recording IDs
  survey_info <- getAudioIDs(con, recordingNames)

  # Get template IDs
  template_info <- getTemplateIDs(con, templateNames)
  
  # Read in templates from AMML(s)
  templates <- loadTemplates(template_info, ammlPath)
  binTemplates <- templates$binTemplates
  corTemplates <- templates$corTemplates


  if (is.null(binTemplates) && is.null(corTemplates)) {
    stop("No templates were found in the AMMonitor model libraries.")
  }

  # Assign new score thresholds (if given)
  if (any(!is.na(scoreThresholds))) {
    if (!is.null(binTemplates)) {
      binScores <- scoreThresholds[which(names(scoreThresholds) %in% monitoR::templateNames(binTemplates))]
      
      if (length(binScores) > 0) {
        monitoR::templateCutoff(binTemplates) <- binScores
      }
    }

    if (!is.null(corTemplates)) {
      corScores <- scoreThresholds[which(names(scoreThresholds) %in% monitoR::templateNames(corTemplates))]
      if (length(corScores) > 0) {
        monitoR::templateCutoff(corTemplates) <- corScores
      }
    }
  }

  # Get combinations of templates and recordings that haven't been run before
  if (dbInsert == TRUE) {
    # Query database for existing model outputs
    recordings_str <- paste(survey_info$pk_mediaid, collapse = ', ')
    templates_str <- paste(template_info$pk_modelid, collapse = ', ')
    combos <- DBI::dbGetQuery(
      con,
      paste0(
        "SELECT fk_mediaid, fk_modelid, MIN(value_num) AS min_score
      FROM modeloutputs
      WHERE fk_mediaid IN (", recordings_str, ") AND fk_modelid IN (", templates_str, ")
      GROUP BY fk_mediaid, fk_modelid;"
      )
    )

    # Make list of which IDs shouldn't be rerun
    dup_runs <- list()
    for (recording in unique(combos$fk_mediaid)) {
      recordingStr <- as.character(recording)
      dup_runs[[recordingStr]] <- character(0)

      # Check if each template is present and score cutoff is higher than what's in the db
      for (template in unique(combos$fk_modelid)) {
        temp_info <- template_info[which(template_info$pk_modelid == template),]
        template_name <- temp_info$model_name

        if (grepl("bin", temp_info$model_type, ignore.case = TRUE) && !is.null(binTemplates)) {
          temp_cutoff <- monitoR::templateCutoff(binTemplates)[template_name]
        } else if (grepl("cor", temp_info$model_type, ignore.case = TRUE) && !is.null(corTemplates)) {
          temp_cutoff <- monitoR::templateCutoff(corTemplates)[template_name]
        } else {
          message(paste0("Can't determine class of template ", template_name, ", skipping checks."))
          next
        }

        min_score <- combos[which(combos$fk_mediaid == recording & combos$fk_modelid == template), 'min_score']

        if (!length(min_score) == 0) {
          if (!is.na(min_score) && min_score <= temp_cutoff) {
            dup_runs[[recordingStr]] <- c(dup_runs[[recordingStr]], template_name)
          }
        }
      }
    }
  }

  # Remove trailing slash in root path
  if (grepl("\\/$", recordingRootPath)) {
    recordingRootPath <- substr(recordingRootPath, 1, nchar(recordingRootPath) - 1)
  }

  scores <- data.frame(
    fk_mediaid = integer(0),
    fk_modelid = integer(0),
    fk_taxonid = character(0),
    x_min = numeric(0),
    x_max = numeric(0),
    y_min = numeric(0),
    y_max = numeric(0),
    value_num = numeric(0)
  )

  if (showProgress == TRUE) {
    pb <- utils::txtProgressBar(max = nrow(survey_info) * 2, style = 3)
  }

  total_duration_sec <- 0
  start_time <- Sys.time()

  # Run templates for each recording
  for (i in seq_len(nrow(survey_info))) {
    audio_path <- file.path(recordingRootPath, survey_info[i, 'filename'])
    current_audio <- methods::as(
      if (grepl("^www.|^http:|^https:", audio_path)) {
        temp.file <- tempfile()
        utils::download.file(
          url = audio_path,
          destfile = temp.file,
          quiet = TRUE,
          mode = "wb",
          cacheOK = TRUE
        )
        if (!file.exists(temp.file)) stop("File couldn't be downloaded")
        tuneR::readWave(temp.file)
      } else {
        tuneR::readWave(audio_path)
      },
      "Wave")

    total_duration_sec <- total_duration_sec + length(current_audio@left) / current_audio@samp.rate

    # Find matches for binary templates
    if (!is.null(binTemplates)) {

      templates <- binTemplates@templates

      sample_rates <- c()

      for (t in 1:length(templates)) {

        template <- templates[[t]]

        sample_rate <- template@samp.rate

        sample_rates <- c(sample_rates, sample_rate)

      }

      sample_rate <-  unique(sample_rates)

      if (length(sample_rate) != 1) {
        stop("The binary templates have different sample rates. Please select only templates with the same sample rate.")
      }
      # resample audio if needed-- seems to need to use the soundgen package
      if (sample_rate != current_audio@samp.rate) {

        current_audio <- seewave::resamp(current_audio,
                                         f = current_audio@samp.rate,
                                         g = sample_rate,
                                         output = "Wave")
        
        message("Resampling audio to match template sample rate.")
      }

      if (dbInsert == TRUE) {
        i_temps <- !(monitoR::templateNames(binTemplates) %in% dup_runs[[as.character(survey_info[i, 'pk_mediaid'])]])
        if (all(i_temps == FALSE)) {
          run_binTemplates <- NULL
          message(paste('Detections for all binary templates for', survey_info[i, 'filename'], 'are already in the database, skipping.'))
        } else {
          run_binTemplates <- methods::new("binTemplateList", templates = binTemplates@templates[i_temps])
        }
      } else {
        run_binTemplates <- binTemplates
      }

      if (!is.null(run_binTemplates)) {
        errorCatch <- tryCatch({
          binScores <- monitoR::binMatch(current_audio, run_binTemplates, write.wav = TRUE, quiet = TRUE)
          finalBinScores <- monitoR::findPeaks(binScores)

          formatted_binScores <- formatDetections(template_info, survey_info[i,], finalBinScores)

          if (dbInsert == TRUE) {
            score_mins <- merge(formatted_binScores, combos, by = c('fk_modelid', 'fk_mediaid'), all.x = TRUE)
            i_keep <- which(score_mins$value_num < score_mins$min_score | is.na(score_mins$min_score))
            message(paste(nrow(formatted_binScores)-length(i_keep), "rows already present in the database have been removed."))
            formatted_binScores <- formatted_binScores[i_keep,]
          }

          scores <- rbind(scores, formatted_binScores)
        },
        error = function(e) {
          e
        },
        finally = unlink('current_audio.wav')
        )

        if (inherits(errorCatch, "error")) {
          message(paste0(
            "There was an issue with file ",
            survey_info[i, 'filename'],
            " while running the binary templates: ",
            errorCatch
          ))
        }

      }
    }

    if (showProgress == TRUE) {
      setTxtProgressBar(pb, 2*i - 1)
    }

    # Find matches for correlation templates
    if (!is.null(corTemplates)) {

      templates <- corTemplates@templates

      sample_rates <- c()

      for (t in 1:length(templates)) {

        template <- templates[[t]]

        sample_rate <- template@samp.rate

        sample_rates <- c(sample_rates, sample_rate)

      }

      sample_rate <-  unique(sample_rates)

      if (length(sample_rate) != 1) {
        stop("The correlation templates have different sample rates. Please select only templates with the same sample rate.")
      }
      # resample audio if needed
      if (sample_rate != current_audio@samp.rate) {

        current_audio <- seewave::resamp(current_audio,
                                         f = current_audio@samp.rate,
                                         g = sample_rate,
                                         output = "Wave")
        
        message("Resampling audio to match template sample rate.")
        
      }

      if (dbInsert == TRUE) {
        i_temps <- !(monitoR::templateNames(corTemplates) %in% dup_runs[[as.character(survey_info[i, 'pk_mediaid'])]])
        if (all(i_temps == FALSE)) {
          run_corTemplates <- NULL
          message(paste('Detections for all correlation templates for', survey_info[i, 'filename'], 'are already in the database, skipping.'))
        }
        run_corTemplates <- methods::new("corTemplateList", templates = corTemplates@templates[i_temps])
      } else {
        run_corTemplates <- corTemplates
      }

      if (!is.null(run_corTemplates)) {
        errorCatch <- tryCatch({

          corScores <- monitoR::corMatch(current_audio, run_corTemplates, cor.method = corMethod, write.wav = TRUE, quiet = TRUE)
          finalCorScores <- monitoR::findPeaks(corScores)

          formatted_corScores <- formatDetections(template_info, survey_info[i,], finalCorScores)

          if (dbInsert == TRUE) {
            score_mins <- merge(formatted_corScores, combos, by = c('fk_modelid', 'fk_mediaid'), all.x = TRUE)
            i_keep <- which(score_mins$value_num < score_mins$min_score | is.na(score_mins$min_score))
            message(paste(nrow(formatted_corScores)-length(i_keep), "rows already present in the database have been removed."))
            formatted_corScores <- formatted_corScores[i_keep,]
          }

          scores <- rbind(scores, formatted_corScores)
        },
        error = function(e) {e},
        finally = unlink('current_audio.wav')
        )

        if (inherits(errorCatch, "error")) {
          message(paste0(
            "There was an issue with file ",
            survey_info[i, 'filename'],
            " while running the correlation templates: ",
            errorCatch
          ))
        }
      }

    }

    if (showProgress == TRUE) {
      setTxtProgressBar(pb, 2*i)
    }
  }

  if (dbInsert == TRUE) {
    DBI::dbAppendTable(
      con,
      'modeloutputs',
      scores
    )
  }

  elapsed_sec <- as.numeric(difftime(Sys.time(), start_time, units = "secs"))
  if (showProgress == TRUE) {
    reportDetectionSpeed(nrow(survey_info), elapsed_sec, total_duration_sec)
  }

  on.exit(unlink('current_audio.wav'))

  return(scores)
}

#' @name getAudioIDs
#' @title Get media IDs and file names for specific audio files
#' @description An internal function that retrieves media IDs and audio files from an AMMonitor database.
#' @param con A connection to a SQLite or Postgres AMMonitor database.
#' @param recordingNames Default = 'all'. An optional character vector specifying
#' by name which recordings should be processed. Default is 'all'.

getAudioIDs <- function(con, recordingNames = 'all') {

  audio_stmnt <- "SELECT pk_mediaid, filename FROM media WHERE media_type = 'audio'"
  if (all(recordingNames == 'all')) {
    # Get all IDs
    audio_info <- DBI::dbGetQuery(con, paste0(audio_stmnt, ";"))

  } else if (is.character(recordingNames)) {
    # Find listed recording IDs in database
    audio_stmnt <- paste0(audio_stmnt, " AND filename IN (")
    audio_params <- list()
    for (i in seq_len(length(recordingNames))) {
      audio_stmnt <- paste0(audio_stmnt, "$", i, ", ")
      audio_params[[i]] <- recordingNames[i]
    }
    audio_stmnt <- substr(audio_stmnt, 1, nchar(audio_stmnt) - 2)
    audio_stmnt <- paste0(audio_stmnt, ")")

    rs <- DBI::dbSendQuery(con, audio_stmnt)
    DBI::dbBind(rs, audio_params)
    audio_info <- DBI::dbFetch(rs)
    DBI::dbClearResult(rs)

  } else {
    stop("Recording names should be a character vector.")
  }

  if (nrow(audio_info) == 0) {
    stop("No recordings were found in the database.")
  }

  return(audio_info)
}

#' @name getTemplateIDs
#' @title Get media IDs and file names for specific audio files
#' @description An internal function that retrieves media IDs and audio files from an AMMonitor database.
#' @param con A connection to a SQLite or Postgres AMMonitor database.
#' @param templateNames Default = 'all'. An optional character vector specifying which templates to use for searching recordings.

getTemplateIDs <- function(con, templateNames = 'all') {

  template_stmnt <- "SELECT pk_modelid, model_name, model_type, amml, fk_taxonid FROM models WHERE model_type LIKE '%emplate%'"
  # Get template IDs
  if (all(templateNames == 'all')) {
    # Get all templates
    template_info <- DBI::dbGetQuery(con, template_stmnt)

  } else if (is.character(templateNames)) {
    # Get listed templates
    template_stmnt <- paste0(template_stmnt, " AND model_name IN (")
    template_params <- list()
    for (i in seq_len(length(templateNames))) {
      template_stmnt <- paste0(template_stmnt, "$", i, ", ")
      template_params[[i]] <- templateNames[i]
    }
    template_stmnt <- substr(template_stmnt, 1, nchar(template_stmnt) - 2)
    template_stmnt <- paste0(template_stmnt, ");")

    rs <- DBI::dbSendQuery(con, template_stmnt)
    DBI::dbBind(rs, template_params)
    template_info <- DBI::dbFetch(rs)
    DBI::dbClearResult(rs)
  } else {
    stop("Template IDs must be a character vector.")
  }

  if (nrow(template_info) == 0) {
    stop("No templates were found in the database.")
  }

  return(template_info)
}

#' @name loadTemplates
#' @title Get templates from one or more AMModels libraries
#' @description An internal function that retrieves templates from AMModels libraries.
#' @param template_info A dataframe containing information about templates, as stored in the AMMonitor database
#' @param ammlPath A character string indicating the path to the directory where AMModels Libraries are stored.

loadTemplates <- function(template_info, ammlPath = "/ammls") {
  # Remove trailing slash in root path
  if (grepl("\\/$", ammlPath)) {
    ammlPath <- substr(ammlPath, 1, nchar(ammlPath) - 1)
  }
  templates <- list()
  for (amml in unique(template_info$amml)) {
    modelLib <- readRDS(file.path(ammlPath, amml))
    if (methods::is(modelLib, "amModelLib")) {
      for (temp_name in template_info[which(template_info$amml == amml), 'model_name']) {
        tryCatch(
          {
            temp <- AMModels::getAMModel(modelLib, temp_name)
            if (methods::is(temp, 'binTemplateList')) {
              if (is.null(templates[['binTemplates']])) {
                templates[['binTemplates']] <- temp
              } else {
                templates[['binTemplates']] <- monitoR::combineBinTemplates(templates[['binTemplates']], temp)
              }
            } else if (methods::is(temp, 'corTemplateList')) {
              if (is.null(templates[['corTemplates']])) {
                templates[['corTemplates']] <- temp
              } else {
                templates[['corTemplates']] <- monitoR::combineCorTemplates(templates[['corTemplates']], temp)
              }
            }
          },
          error = function(e) {
            message(paste0('Template ', temp_name, ' not found in model library ', amml, ', skipping.'))
          }
        )
      }
    }
  }
  return(templates)
}

#' @name formatDetections
#' @title Formats detections from a detectionList object to fit the AMMonitor database
#' @description An internal function formats detectionList detections for insertion into the AMMonitor database.
#' @param template_info A dataframe containing information about templates stored in the AMMonitor database
#' @param recording_info A one-row dataframe containing information about an audio recording stored in the AMMonitor database.
#' @param detections A detectionList object, returned after running binMatch or corMatch

formatDetections <- function(template_info, recording_info, detections) {
  # Empty dataframe in AMMonitor format
  scores <- data.frame(
    fk_mediaid = integer(0),
    fk_modelid = integer(0),
    fk_taxonid = character(0),
    x_min = numeric(0),
    x_max = numeric(0),
    y_min = numeric(0),
    y_max = numeric(0),
    value_num = numeric(0)
  )

  # loop through each template
  for (temp_name in names(detections@detections)) {
    # format detections to fit AMMonitor database
    temp_info <- template_info[which(template_info$model_name == temp_name),]
    temp_half_duration <- detections@templates[[temp_name]]@duration/2
    temp_scores <- detections@detections[[temp_name]][c('time', 'score')]

    if (nrow(temp_scores) == 0) {
      next
    }

    names(temp_scores) <- c('time', 'value_num')

    # add foreign key data
    temp_scores$fk_mediaid <- recording_info$pk_mediaid
    temp_scores$fk_modelid <- temp_info$pk_modelid
    temp_scores$fk_taxonid <- temp_info$fk_taxonid

    # add bounding box
    temp_scores$x_min <- round(temp_scores$time - temp_half_duration, 4)
    temp_scores$x_max <- round(temp_scores$time + temp_half_duration, 4)
    temp_scores$y_min <- round(detections@templates[[temp_name]]@frq.lim[1], 4)
    temp_scores$y_max <- round(detections@templates[[temp_name]]@frq.lim[2], 4)

    temp_scores <- temp_scores[c('fk_mediaid', 'fk_modelid', 'fk_taxonid', 'x_min', 'x_max', 'y_min', 'y_max', 'value_num')]

    scores <- rbind(scores, temp_scores)
  }
  return(scores)
}
